# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/modelproperties.ui'
#

#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ModelProperties(object):
    def setupUi(self, ModelProperties):
        ModelProperties.setObjectName("ModelProperties")
        ModelProperties.setWindowModality(QtCore.Qt.ApplicationModal)
        ModelProperties.resize(471, 435)
        self.verticalLayout = QtGui.QVBoxLayout(ModelProperties)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(ModelProperties)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setContentsMargins(4, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.name = QtGui.QLineEdit(self.groupBox)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(ModelProperties)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cardList = QtGui.QListWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cardList.sizePolicy().hasHeightForWidth())
        self.cardList.setSizePolicy(sizePolicy)
        self.cardList.setMinimumSize(QtCore.QSize(0, 60))
        self.cardList.setObjectName("cardList")
        self.gridLayout_4.addWidget(self.cardList, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cardAdd = QtGui.QPushButton(self.groupBox_2)
        self.cardAdd.setObjectName("cardAdd")
        self.verticalLayout_4.addWidget(self.cardAdd)
        self.cardRename = QtGui.QPushButton(self.groupBox_2)
        self.cardRename.setObjectName("cardRename")
        self.verticalLayout_4.addWidget(self.cardRename)
        self.cardUp = QtGui.QPushButton(self.groupBox_2)
        self.cardUp.setObjectName("cardUp")
        self.verticalLayout_4.addWidget(self.cardUp)
        self.cardDown = QtGui.QPushButton(self.groupBox_2)
        self.cardDown.setObjectName("cardDown")
        self.verticalLayout_4.addWidget(self.cardDown)
        self.cardToggle = QtGui.QPushButton(self.groupBox_2)
        self.cardToggle.setText("")
        self.cardToggle.setObjectName("cardToggle")
        self.verticalLayout_4.addWidget(self.cardToggle)
        self.cardDelete = QtGui.QPushButton(self.groupBox_2)
        self.cardDelete.setObjectName("cardDelete")
        self.verticalLayout_4.addWidget(self.cardDelete)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.cardLayout = QtGui.QPushButton(self.groupBox_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/layout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cardLayout.setIcon(icon)
        self.cardLayout.setObjectName("cardLayout")
        self.verticalLayout_4.addWidget(self.cardLayout)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtGui.QDialogButtonBox(ModelProperties)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ModelProperties)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ModelProperties.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ModelProperties.reject)
        QtCore.QMetaObject.connectSlotsByName(ModelProperties)
        ModelProperties.setTabOrder(self.name, self.cardList)
        ModelProperties.setTabOrder(self.cardList, self.cardAdd)
        ModelProperties.setTabOrder(self.cardAdd, self.cardRename)
        ModelProperties.setTabOrder(self.cardRename, self.cardUp)
        ModelProperties.setTabOrder(self.cardUp, self.cardDown)
        ModelProperties.setTabOrder(self.cardDown, self.cardToggle)
        ModelProperties.setTabOrder(self.cardToggle, self.cardDelete)
        ModelProperties.setTabOrder(self.cardDelete, self.cardLayout)
        ModelProperties.setTabOrder(self.cardLayout, self.buttonBox)

    def retranslateUi(self, ModelProperties):
        ModelProperties.setWindowTitle(_("Model Properties"))
        self.groupBox.setTitle(_("General"))
        self.label_2.setText(_("Name"))
        self.groupBox_2.setTitle(_("Card Templates"))
        self.cardAdd.setText(_("&Add"))
        self.cardRename.setText(_("&Rename"))
        self.cardUp.setToolTip(_("Move selected card model up"))
        self.cardUp.setText(_("&Up"))
        self.cardDown.setToolTip(_("Move selected card model down"))
        self.cardDown.setText(_("Dow&n"))
        self.cardDelete.setText(_("&Delete"))
        self.cardLayout.setText(_("Card &Layout"))

import icons_rc
