# This file auto-generated by build_ui.sh. Don't edit.
__all__ = [
	"about",
	"addcards",
	"addfield",
	"addmodel",
	"browser",
	"browserdisp",
	"browseropts",
	"changemap",
	"changemodel",
	"customstudy",
	"dconf",
	"debug",
	"dyndconf",
	"editaddon",
	"editcurrent",
	"edithtml",
	"exporting",
	"fields",
	"finddupes",
	"findreplace",
	"getaddons",
	"importing",
	"main",
	"modelopts",
	"models",
	"preferences",
	"preview",
	"profiles",
	"reposition",
	"reschedule",
	"setgroup",
	"setlang",
	"stats",
	"studydeck",
	"taglimit",
	"template",
]
import about
import addcards
import addfield
import addmodel
import browser
import browserdisp
import browseropts
import changemap
import changemodel
import customstudy
import dconf
import debug
import dyndconf
import editaddon
import editcurrent
import edithtml
import exporting
import fields
import finddupes
import findreplace
import getaddons
import importing
import main
import modelopts
import models
import preferences
import preview
import profiles
import reposition
import reschedule
import setgroup
import setlang
import stats
import studydeck
import taglimit
import template
