# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/dconf.ui'
#
# Created: Thu Dec 22 13:02:39 2016
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(494, 454)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_31 = QtGui.QLabel(Dialog)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_2.addWidget(self.label_31)
        self.dconf = QtGui.QComboBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dconf.sizePolicy().hasHeightForWidth())
        self.dconf.setSizePolicy(sizePolicy)
        self.dconf.setObjectName(_fromUtf8("dconf"))
        self.horizontalLayout_2.addWidget(self.dconf)
        self.confOpts = QtGui.QToolButton(Dialog)
        self.confOpts.setMaximumSize(QtCore.QSize(16777215, 32))
        self.confOpts.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/gears.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.confOpts.setIcon(icon)
        self.confOpts.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.confOpts.setArrowType(QtCore.Qt.NoArrow)
        self.confOpts.setObjectName(_fromUtf8("confOpts"))
        self.horizontalLayout_2.addWidget(self.confOpts)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.count = QtGui.QLabel(Dialog)
        self.count.setStyleSheet(_fromUtf8("* { color: red }"))
        self.count.setText(_fromUtf8(""))
        self.count.setAlignment(QtCore.Qt.AlignCenter)
        self.count.setWordWrap(True)
        self.count.setObjectName(_fromUtf8("count"))
        self.verticalLayout.addWidget(self.count)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_27 = QtGui.QLabel(self.tab)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 5, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 5, 0, 1, 1)
        self.lrnFactor = QtGui.QSpinBox(self.tab)
        self.lrnFactor.setMinimum(130)
        self.lrnFactor.setMaximum(999)
        self.lrnFactor.setObjectName(_fromUtf8("lrnFactor"))
        self.gridLayout.addWidget(self.lrnFactor, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.lrnEasyInt = QtGui.QSpinBox(self.tab)
        self.lrnEasyInt.setMinimum(1)
        self.lrnEasyInt.setObjectName(_fromUtf8("lrnEasyInt"))
        self.gridLayout.addWidget(self.lrnEasyInt, 4, 1, 1, 1)
        self.lrnGradInt = QtGui.QSpinBox(self.tab)
        self.lrnGradInt.setMinimum(1)
        self.lrnGradInt.setObjectName(_fromUtf8("lrnGradInt"))
        self.gridLayout.addWidget(self.lrnGradInt, 3, 1, 1, 1)
        self.newplim = QtGui.QLabel(self.tab)
        self.newplim.setText(_fromUtf8(""))
        self.newplim.setObjectName(_fromUtf8("newplim"))
        self.gridLayout.addWidget(self.newplim, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.newPerDay = QtGui.QSpinBox(self.tab)
        self.newPerDay.setMaximum(9999)
        self.newPerDay.setObjectName(_fromUtf8("newPerDay"))
        self.gridLayout.addWidget(self.newPerDay, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.lrnSteps = QtGui.QLineEdit(self.tab)
        self.lrnSteps.setObjectName(_fromUtf8("lrnSteps"))
        self.gridLayout.addWidget(self.lrnSteps, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.newOrder = QtGui.QComboBox(self.tab)
        self.newOrder.setObjectName(_fromUtf8("newOrder"))
        self.gridLayout.addWidget(self.newOrder, 1, 1, 1, 2)
        self.bury = QtGui.QCheckBox(self.tab)
        self.bury.setObjectName(_fromUtf8("bury"))
        self.gridLayout.addWidget(self.bury, 6, 0, 1, 3)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 1, 0, 1, 1)
        self.easyBonus = QtGui.QSpinBox(self.tab_3)
        self.easyBonus.setMinimum(100)
        self.easyBonus.setMaximum(1000)
        self.easyBonus.setSingleStep(5)
        self.easyBonus.setObjectName(_fromUtf8("easyBonus"))
        self.gridLayout_3.addWidget(self.easyBonus, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 1, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab_3)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_3.addWidget(self.label_34, 2, 2, 1, 1)
        self.revPerDay = QtGui.QSpinBox(self.tab_3)
        self.revPerDay.setMinimum(0)
        self.revPerDay.setMaximum(9999)
        self.revPerDay.setObjectName(_fromUtf8("revPerDay"))
        self.gridLayout_3.addWidget(self.revPerDay, 0, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_3.addWidget(self.label_33, 2, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.tab_3)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_3.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.maxIvl = QtGui.QSpinBox(self.tab_3)
        self.maxIvl.setMinimum(1)
        self.maxIvl.setMaximum(99999)
        self.maxIvl.setObjectName(_fromUtf8("maxIvl"))
        self.gridLayout_3.addWidget(self.maxIvl, 3, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 3, 2, 1, 1)
        self.revplim = QtGui.QLabel(self.tab_3)
        self.revplim.setText(_fromUtf8(""))
        self.revplim.setObjectName(_fromUtf8("revplim"))
        self.gridLayout_3.addWidget(self.revplim, 0, 2, 1, 1)
        self.fi1 = QtGui.QDoubleSpinBox(self.tab_3)
        self.fi1.setDecimals(0)
        self.fi1.setMinimum(0.0)
        self.fi1.setMaximum(999.0)
        self.fi1.setSingleStep(1.0)
        self.fi1.setProperty("value", 100.0)
        self.fi1.setObjectName(_fromUtf8("fi1"))
        self.gridLayout_3.addWidget(self.fi1, 2, 1, 1, 1)
        self.buryRev = QtGui.QCheckBox(self.tab_3)
        self.buryRev.setObjectName(_fromUtf8("buryRev"))
        self.gridLayout_3.addWidget(self.buryRev, 4, 0, 1, 3)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 152, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 1)
        self.lapSteps = QtGui.QLineEdit(self.tab_2)
        self.lapSteps.setObjectName(_fromUtf8("lapSteps"))
        self.gridLayout_2.addWidget(self.lapSteps, 0, 1, 1, 2)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.leechThreshold = QtGui.QSpinBox(self.tab_2)
        self.leechThreshold.setObjectName(_fromUtf8("leechThreshold"))
        self.gridLayout_2.addWidget(self.leechThreshold, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.lapMinInt = QtGui.QSpinBox(self.tab_2)
        self.lapMinInt.setMinimum(1)
        self.lapMinInt.setMaximum(99)
        self.lapMinInt.setObjectName(_fromUtf8("lapMinInt"))
        self.gridLayout_2.addWidget(self.lapMinInt, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 2, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leechAction = QtGui.QComboBox(self.tab_2)
        self.leechAction.setObjectName(_fromUtf8("leechAction"))
        self.leechAction.addItem(_fromUtf8(""))
        self.leechAction.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.leechAction)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 1, 1, 2)
        self.label_28 = QtGui.QLabel(self.tab_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 1, 2, 1, 1)
        self.lapMult = QtGui.QSpinBox(self.tab_2)
        self.lapMult.setMaximum(100)
        self.lapMult.setSingleStep(5)
        self.lapMult.setObjectName(_fromUtf8("lapMult"))
        self.gridLayout_2.addWidget(self.lapMult, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 72, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_25 = QtGui.QLabel(self.tab_5)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 0, 0, 1, 1)
        self.maxTaken = QtGui.QSpinBox(self.tab_5)
        self.maxTaken.setMinimum(30)
        self.maxTaken.setMaximum(3600)
        self.maxTaken.setSingleStep(10)
        self.maxTaken.setObjectName(_fromUtf8("maxTaken"))
        self.gridLayout_5.addWidget(self.maxTaken, 0, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_5.addWidget(self.label_26, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.showTimer = QtGui.QCheckBox(self.tab_5)
        self.showTimer.setObjectName(_fromUtf8("showTimer"))
        self.verticalLayout_6.addWidget(self.showTimer)
        self.autoplaySounds = QtGui.QCheckBox(self.tab_5)
        self.autoplaySounds.setObjectName(_fromUtf8("autoplaySounds"))
        self.verticalLayout_6.addWidget(self.autoplaySounds)
        self.replayQuestion = QtGui.QCheckBox(self.tab_5)
        self.replayQuestion.setChecked(False)
        self.replayQuestion.setObjectName(_fromUtf8("replayQuestion"))
        self.verticalLayout_6.addWidget(self.replayQuestion)
        spacerItem4 = QtGui.QSpacerItem(20, 199, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_5.addWidget(self.label_22)
        self.desc = QtGui.QTextEdit(self.tab_4)
        self.desc.setObjectName(_fromUtf8("desc"))
        self.verticalLayout_5.addWidget(self.desc)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.dconf, self.confOpts)
        Dialog.setTabOrder(self.confOpts, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.lrnSteps)
        Dialog.setTabOrder(self.lrnSteps, self.newOrder)
        Dialog.setTabOrder(self.newOrder, self.newPerDay)
        Dialog.setTabOrder(self.newPerDay, self.lrnGradInt)
        Dialog.setTabOrder(self.lrnGradInt, self.lrnEasyInt)
        Dialog.setTabOrder(self.lrnEasyInt, self.lrnFactor)
        Dialog.setTabOrder(self.lrnFactor, self.bury)
        Dialog.setTabOrder(self.bury, self.revPerDay)
        Dialog.setTabOrder(self.revPerDay, self.easyBonus)
        Dialog.setTabOrder(self.easyBonus, self.fi1)
        Dialog.setTabOrder(self.fi1, self.maxIvl)
        Dialog.setTabOrder(self.maxIvl, self.buryRev)
        Dialog.setTabOrder(self.buryRev, self.lapSteps)
        Dialog.setTabOrder(self.lapSteps, self.lapMult)
        Dialog.setTabOrder(self.lapMult, self.lapMinInt)
        Dialog.setTabOrder(self.lapMinInt, self.leechThreshold)
        Dialog.setTabOrder(self.leechThreshold, self.leechAction)
        Dialog.setTabOrder(self.leechAction, self.maxTaken)
        Dialog.setTabOrder(self.maxTaken, self.showTimer)
        Dialog.setTabOrder(self.showTimer, self.autoplaySounds)
        Dialog.setTabOrder(self.autoplaySounds, self.replayQuestion)
        Dialog.setTabOrder(self.replayQuestion, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.desc)

    def retranslateUi(self, Dialog):
        self.label_31.setText(_("Options group:"))
        self.label_27.setText(_("%"))
        self.label_24.setText(_("Starting ease"))
        self.label_8.setText(_("Order"))
        self.label_5.setText(_("Easy interval"))
        self.label_4.setText(_("Graduating interval"))
        self.label_6.setText(_("New cards/day"))
        self.label_2.setText(_("Steps (in minutes)"))
        self.bury.setText(_("Bury related new cards until the next day"))
        self.label_9.setText(_("days"))
        self.label_7.setText(_("days"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _("New Cards"))
        self.label_20.setText(_("Easy bonus"))
        self.label_21.setText(_("%"))
        self.label_34.setText(_("%"))
        self.label_33.setText(_("Interval modifier"))
        self.label_37.setText(_("Maximum reviews/day"))
        self.label_3.setText(_("Maximum interval"))
        self.label_23.setText(_("days"))
        self.buryRev.setText(_("Bury related reviews until the next day"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _("Reviews"))
        self.label_17.setText(_("Steps (in minutes)"))
        self.label.setText(_("New interval"))
        self.label_10.setText(_("Leech threshold"))
        self.label_11.setText(_("lapses"))
        self.label_12.setText(_("Leech action"))
        self.label_13.setText(_("Minimum interval"))
        self.label_14.setText(_("days"))
        self.leechAction.setItemText(0, _("Suspend Card"))
        self.leechAction.setItemText(1, _("Tag Only"))
        self.label_28.setText(_("%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("Lapses"))
        self.label_25.setText(_("Ignore answer times longer than"))
        self.label_26.setText(_("seconds"))
        self.showTimer.setText(_("Show answer timer"))
        self.autoplaySounds.setText(_("Automatically play audio"))
        self.replayQuestion.setText(_("When answer shown, replay both question and answer audio"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _("General"))
        self.label_22.setText(_("Description to show on study screen (current deck only):"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _("Description"))

import icons_rc
