# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/preferences.ui'
#
# Created: Thu Dec 22 13:02:40 2016
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName(_fromUtf8("Preferences"))
        Preferences.resize(405, 455)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Preferences)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Preferences)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab_1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.lang = QtGui.QComboBox(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lang.sizePolicy().hasHeightForWidth())
        self.lang.setSizePolicy(sizePolicy)
        self.lang.setObjectName(_fromUtf8("lang"))
        self.horizontalLayout_2.addWidget(self.lang)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.showEstimates = QtGui.QCheckBox(self.tab_1)
        self.showEstimates.setObjectName(_fromUtf8("showEstimates"))
        self.verticalLayout.addWidget(self.showEstimates)
        self.showProgress = QtGui.QCheckBox(self.tab_1)
        self.showProgress.setObjectName(_fromUtf8("showProgress"))
        self.verticalLayout.addWidget(self.showProgress)
        self.stripHTML = QtGui.QCheckBox(self.tab_1)
        self.stripHTML.setObjectName(_fromUtf8("stripHTML"))
        self.verticalLayout.addWidget(self.stripHTML)
        self.pastePNG = QtGui.QCheckBox(self.tab_1)
        self.pastePNG.setObjectName(_fromUtf8("pastePNG"))
        self.verticalLayout.addWidget(self.pastePNG)
        self.useCurrent = QtGui.QComboBox(self.tab_1)
        self.useCurrent.setObjectName(_fromUtf8("useCurrent"))
        self.useCurrent.addItem(_fromUtf8(""))
        self.useCurrent.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.useCurrent)
        self.newSpread = QtGui.QComboBox(self.tab_1)
        self.newSpread.setObjectName(_fromUtf8("newSpread"))
        self.verticalLayout.addWidget(self.newSpread)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_23 = QtGui.QLabel(self.tab_1)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 0, 0, 1, 1)
        self.dayOffset = QtGui.QSpinBox(self.tab_1)
        self.dayOffset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.dayOffset.setMaximum(23)
        self.dayOffset.setObjectName(_fromUtf8("dayOffset"))
        self.gridLayout_4.addWidget(self.dayOffset, 0, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_1)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.lrnCutoff = QtGui.QSpinBox(self.tab_1)
        self.lrnCutoff.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lrnCutoff.setMaximum(999)
        self.lrnCutoff.setObjectName(_fromUtf8("lrnCutoff"))
        self.gridLayout_4.addWidget(self.lrnCutoff, 1, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_1)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 1, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_1)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 2, 0, 1, 1)
        self.timeLimit = QtGui.QSpinBox(self.tab_1)
        self.timeLimit.setMaximum(9999)
        self.timeLimit.setObjectName(_fromUtf8("timeLimit"))
        self.gridLayout_4.addWidget(self.timeLimit, 2, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.tab_1)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_4.addWidget(self.label_39, 2, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.tab_1)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_4.addWidget(self.label_40, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.profilePass = QtGui.QPushButton(self.tab_1)
        self.profilePass.setAutoDefault(False)
        self.profilePass.setObjectName(_fromUtf8("profilePass"))
        self.verticalLayout.addWidget(self.profilePass)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(10)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.syncLabel = QtGui.QLabel(self.tab_2)
        self.syncLabel.setWordWrap(True)
        self.syncLabel.setOpenExternalLinks(True)
        self.syncLabel.setObjectName(_fromUtf8("syncLabel"))
        self.vboxlayout.addWidget(self.syncLabel)
        self.syncMedia = QtGui.QCheckBox(self.tab_2)
        self.syncMedia.setObjectName(_fromUtf8("syncMedia"))
        self.vboxlayout.addWidget(self.syncMedia)
        self.syncOnProgramOpen = QtGui.QCheckBox(self.tab_2)
        self.syncOnProgramOpen.setObjectName(_fromUtf8("syncOnProgramOpen"))
        self.vboxlayout.addWidget(self.syncOnProgramOpen)
        self.fullSync = QtGui.QCheckBox(self.tab_2)
        self.fullSync.setObjectName(_fromUtf8("fullSync"))
        self.vboxlayout.addWidget(self.fullSync)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.syncDeauth = QtGui.QPushButton(self.tab_2)
        self.syncDeauth.setAutoDefault(False)
        self.syncDeauth.setObjectName(_fromUtf8("syncDeauth"))
        self.horizontalLayout.addWidget(self.syncDeauth)
        self.syncUser = QtGui.QLabel(self.tab_2)
        self.syncUser.setText(_fromUtf8(""))
        self.syncUser.setObjectName(_fromUtf8("syncUser"))
        self.horizontalLayout.addWidget(self.syncUser)
        spacerItem1 = QtGui.QSpacerItem(40, 1, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.vboxlayout.addLayout(self.horizontalLayout)
        self.hboxlayout.addLayout(self.vboxlayout)
        self.verticalLayout_4.addLayout(self.hboxlayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.numBackups = QtGui.QSpinBox(self.tab)
        self.numBackups.setMinimumSize(QtCore.QSize(60, 0))
        self.numBackups.setMaximumSize(QtCore.QSize(60, 16777215))
        self.numBackups.setObjectName(_fromUtf8("numBackups"))
        self.gridLayout_2.addWidget(self.numBackups, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.compressBackups = QtGui.QCheckBox(self.tab)
        self.compressBackups.setObjectName(_fromUtf8("compressBackups"))
        self.verticalLayout_3.addWidget(self.compressBackups)
        self.openBackupFolder = QtGui.QLabel(self.tab)
        self.openBackupFolder.setObjectName(_fromUtf8("openBackupFolder"))
        self.verticalLayout_3.addWidget(self.openBackupFolder)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        spacerItem4 = QtGui.QSpacerItem(20, 59, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_3.addWidget(self.label_21)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Preferences)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Preferences.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Preferences.reject)
        QtCore.QMetaObject.connectSlotsByName(Preferences)
        Preferences.setTabOrder(self.lang, self.showEstimates)
        Preferences.setTabOrder(self.showEstimates, self.showProgress)
        Preferences.setTabOrder(self.showProgress, self.stripHTML)
        Preferences.setTabOrder(self.stripHTML, self.pastePNG)
        Preferences.setTabOrder(self.pastePNG, self.useCurrent)
        Preferences.setTabOrder(self.useCurrent, self.newSpread)
        Preferences.setTabOrder(self.newSpread, self.dayOffset)
        Preferences.setTabOrder(self.dayOffset, self.lrnCutoff)
        Preferences.setTabOrder(self.lrnCutoff, self.timeLimit)
        Preferences.setTabOrder(self.timeLimit, self.profilePass)
        Preferences.setTabOrder(self.profilePass, self.syncMedia)
        Preferences.setTabOrder(self.syncMedia, self.syncOnProgramOpen)
        Preferences.setTabOrder(self.syncOnProgramOpen, self.syncDeauth)
        Preferences.setTabOrder(self.syncDeauth, self.numBackups)
        Preferences.setTabOrder(self.numBackups, self.buttonBox)
        Preferences.setTabOrder(self.buttonBox, self.tabWidget)
        Preferences.setTabOrder(self.tabWidget, self.fullSync)
        Preferences.setTabOrder(self.fullSync, self.compressBackups)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(_("Preferences"))
        self.label.setText(_("Interface language:"))
        self.showEstimates.setText(_("Show next review time above answer buttons"))
        self.showProgress.setText(_("Show remaining card count during review"))
        self.stripHTML.setText(_("Strip HTML when pasting text"))
        self.pastePNG.setText(_("Paste clipboard images as PNG"))
        self.useCurrent.setItemText(0, _("When adding, default to current deck"))
        self.useCurrent.setItemText(1, _("Change deck depending on note type"))
        self.label_23.setText(_("Next day starts at"))
        self.label_24.setText(_("Learn ahead limit"))
        self.label_29.setText(_("mins"))
        self.label_30.setText(_("Timebox time limit"))
        self.label_39.setText(_("mins"))
        self.label_40.setText(_("hours past midnight"))
        self.profilePass.setText(_("Profile Password..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _("Basic"))
        self.syncLabel.setText(_("<b>Synchronisation</b>"))
        self.syncMedia.setText(_("Synchronize audio and images too"))
        self.syncOnProgramOpen.setText(_("Automatically sync on profile open/close"))
        self.fullSync.setText(_("On next sync, force changes in one direction"))
        self.syncDeauth.setText(_("Deauthorize"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("Network"))
        self.label_9.setText(_("<b>Backups</b><br>Anki will create a backup of your collection each time it is closed or synchronized."))
        self.label_10.setText(_("Keep"))
        self.label_11.setText(_("backups"))
        self.compressBackups.setText(_("Compress backups (slower)"))
        self.openBackupFolder.setText(_("<a href=\"backups\">Open backup folder</a>"))
        self.label_4.setText(_("Note: Media is not backed up. Please create a periodic backup of your Anki folder to be safe."))
        self.label_21.setText(_("Some settings will take effect after you restart Anki."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _("Backups"))

