#!/bin/sh
# This script takes a anki-x.y.z.tgz source file and creates a
# anki_x.y.z.orig.tar.gz with the sample file libanki/samples/RTK1+3.anki
# removed.  It's a collection from Heisig's Remembering The Kanji series
# and therefore with possible copyright issues.

dir=
src="${1##*/}"
if [ "$src" != "$1" ]; then
	dir="${1%/*}/"
fi

case "$src" in
anki-*.tgz)
	;;
"")
	echo "No source given"
	exit 1
	;;
*)
	echo "Filename not in supported format (anki-*.tgz)"
	exit 1
	;;
esac

version=${src#anki-}
version=${version%.tgz}
src="$dir$src"
dest="${dir}anki_${version}.orig.tar"

echo "$src is version $version"

zcat "$src" >"$dest"
tar -f "$dest" --delete "anki-${version}/libanki/samples/RTK1+3.anki"
gzip -9 "$dest"
