# This file auto-generated by build_ui.sh. Don't edit.
__all__ = [
	"about",
	"activetags",
	"addcardmodels",
	"addcards",
	"addmodel",
	"cardlist",
	"changemap",
	"changemodel",
	"clayout",
	"deckproperties",
	"editfont",
	"edithtml",
	"exporting",
	"finddupes",
	"findreplace",
	"getshared",
	"importing",
	"importup",
	"main",
	"modelproperties",
	"preferences",
	"reschedule",
	"share",
	"syncdeck",
]
import about
import activetags
import addcardmodels
import addcards
import addmodel
import cardlist
import changemap
import changemodel
import clayout
import deckproperties
import editfont
import edithtml
import exporting
import finddupes
import findreplace
import getshared
import importing
import importup
import main
import modelproperties
import preferences
import reschedule
import share
import syncdeck
