# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/clayout.ui'
#

#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 482)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtGui.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.templateLayout = QtGui.QGridLayout()
        self.templateLayout.setMargin(0)
        self.templateLayout.setSpacing(6)
        self.templateLayout.setObjectName("templateLayout")
        self.cardQuestion = QtGui.QTextEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardQuestion.sizePolicy().hasHeightForWidth())
        self.cardQuestion.setSizePolicy(sizePolicy)
        self.cardQuestion.setMinimumSize(QtCore.QSize(50, 0))
        self.cardQuestion.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cardQuestion.setTabChangesFocus(True)
        self.cardQuestion.setObjectName("cardQuestion")
        self.templateLayout.addWidget(self.cardQuestion, 3, 1, 1, 1)
        self.cardAnswer = QtGui.QTextEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardAnswer.sizePolicy().hasHeightForWidth())
        self.cardAnswer.setSizePolicy(sizePolicy)
        self.cardAnswer.setMinimumSize(QtCore.QSize(50, 0))
        self.cardAnswer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cardAnswer.setTabChangesFocus(True)
        self.cardAnswer.setAcceptRichText(False)
        self.cardAnswer.setObjectName("cardAnswer")
        self.templateLayout.addWidget(self.cardAnswer, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cardList = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardList.sizePolicy().hasHeightForWidth())
        self.cardList.setSizePolicy(sizePolicy)
        self.cardList.setObjectName("cardList")
        self.horizontalLayout_2.addWidget(self.cardList)
        self.editTemplates = QtGui.QPushButton(self.tab)
        self.editTemplates.setObjectName("editTemplates")
        self.horizontalLayout_2.addWidget(self.editTemplates)
        self.templateLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setOpenExternalLinks(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.flipButton = QtGui.QPushButton(self.tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/multisynk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flipButton.setIcon(icon)
        self.flipButton.setObjectName("flipButton")
        self.verticalLayout_6.addWidget(self.flipButton)
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setOpenExternalLinks(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.templateLayout.addLayout(self.verticalLayout_6, 3, 0, 2, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.templateLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.alignment = QtGui.QComboBox(self.tab)
        self.alignment.setObjectName("alignment")
        self.templateLayout.addWidget(self.alignment, 5, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.templateLayout.addWidget(self.label_16, 6, 0, 1, 1)
        self.background = QtGui.QPushButton(self.tab)
        self.background.setText("")
        self.background.setAutoDefault(False)
        self.background.setObjectName("background")
        self.templateLayout.addWidget(self.background, 6, 1, 1, 1)
        self.templateType = QtGui.QLabel(self.tab)
        self.templateType.setText("")
        self.templateType.setObjectName("templateType")
        self.templateLayout.addWidget(self.templateType, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.templateLayout)
        self.typeAnswer = QtGui.QComboBox(self.tab)
        self.typeAnswer.setObjectName("typeAnswer")
        self.verticalLayout.addWidget(self.typeAnswer)
        self.questionInAnswer = QtGui.QCheckBox(self.tab)
        self.questionInAnswer.setObjectName("questionInAnswer")
        self.verticalLayout.addWidget(self.questionInAnswer)
        self.allowEmptyAnswer = QtGui.QCheckBox(self.tab)
        self.allowEmptyAnswer.setObjectName("allowEmptyAnswer")
        self.verticalLayout.addWidget(self.allowEmptyAnswer)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fieldList = QtGui.QListWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldList.sizePolicy().hasHeightForWidth())
        self.fieldList.setSizePolicy(sizePolicy)
        self.fieldList.setMinimumSize(QtCore.QSize(50, 60))
        self.fieldList.setObjectName("fieldList")
        self.horizontalLayout.addWidget(self.fieldList)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fieldAdd = QtGui.QPushButton(self.tab_2)
        self.fieldAdd.setAutoDefault(False)
        self.fieldAdd.setObjectName("fieldAdd")
        self.verticalLayout_3.addWidget(self.fieldAdd)
        self.fieldUp = QtGui.QPushButton(self.tab_2)
        self.fieldUp.setAutoDefault(False)
        self.fieldUp.setObjectName("fieldUp")
        self.verticalLayout_3.addWidget(self.fieldUp)
        self.fieldDown = QtGui.QPushButton(self.tab_2)
        self.fieldDown.setAutoDefault(False)
        self.fieldDown.setObjectName("fieldDown")
        self.verticalLayout_3.addWidget(self.fieldDown)
        self.fieldDelete = QtGui.QPushButton(self.tab_2)
        self.fieldDelete.setAutoDefault(False)
        self.fieldDelete.setObjectName("fieldDelete")
        self.verticalLayout_3.addWidget(self.fieldDelete)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self._2 = QtGui.QGridLayout()
        self._2.setMargin(0)
        self._2.setSpacing(6)
        self._2.setObjectName("_2")
        self.fieldName = QtGui.QLineEdit(self.tab_2)
        self.fieldName.setObjectName("fieldName")
        self._2.addWidget(self.fieldName, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self._2.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self._2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self._2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self._2.addWidget(self.label_7, 3, 0, 1, 1)
        self.fontFamily = QtGui.QFontComboBox(self.tab_2)
        self.fontFamily.setMinimumSize(QtCore.QSize(0, 25))
        self.fontFamily.setObjectName("fontFamily")
        self._2.addWidget(self.fontFamily, 1, 1, 1, 1)
        self.fontColour = QtGui.QPushButton(self.tab_2)
        self.fontColour.setAutoFillBackground(True)
        self.fontColour.setText("")
        self.fontColour.setAutoDefault(False)
        self.fontColour.setObjectName("fontColour")
        self._2.addWidget(self.fontColour, 3, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.fontSize = QtGui.QSpinBox(self.tab_2)
        self.fontSize.setMinimum(5)
        self.fontSize.setMaximum(300)
        self.fontSize.setObjectName("fontSize")
        self.gridLayout_2.addWidget(self.fontSize, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 3, 1, 1)
        self.fontSizeEdit = QtGui.QSpinBox(self.tab_2)
        self.fontSizeEdit.setMinimum(5)
        self.fontSizeEdit.setMaximum(300)
        self.fontSizeEdit.setObjectName("fontSizeEdit")
        self.gridLayout_2.addWidget(self.fontSizeEdit, 0, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 5, 1, 1)
        self._2.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self._2.addWidget(self.label_18, 4, 0, 1, 1)
        self.rtl = QtGui.QCheckBox(self.tab_2)
        self.rtl.setObjectName("rtl")
        self._2.addWidget(self.rtl, 8, 1, 1, 1)
        self.numeric = QtGui.QCheckBox(self.tab_2)
        self.numeric.setObjectName("numeric")
        self._2.addWidget(self.numeric, 7, 1, 1, 1)
        self.fieldRequired = QtGui.QCheckBox(self.tab_2)
        self.fieldRequired.setObjectName("fieldRequired")
        self._2.addWidget(self.fieldRequired, 5, 1, 1, 1)
        self.fieldUnique = QtGui.QCheckBox(self.tab_2)
        self.fieldUnique.setObjectName("fieldUnique")
        self._2.addWidget(self.fieldUnique, 4, 1, 1, 1)
        self.preserveWhitespace = QtGui.QCheckBox(self.tab_2)
        self.preserveWhitespace.setObjectName("preserveWhitespace")
        self._2.addWidget(self.preserveWhitespace, 6, 1, 1, 1)
        self.verticalLayout_2.addLayout(self._2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.previewGroup = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewGroup.sizePolicy().hasHeightForWidth())
        self.previewGroup.setSizePolicy(sizePolicy)
        self.previewGroup.setObjectName("previewGroup")
        self._3 = QtGui.QVBoxLayout(self.previewGroup)
        self._3.setSpacing(6)
        self._3.setMargin(6)
        self._3.setObjectName("_3")
        self.preview = QtWebKit.QWebView(self.previewGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview.sizePolicy().hasHeightForWidth())
        self.preview.setSizePolicy(sizePolicy)
        self.preview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.preview.setUrl(QtCore.QUrl("about:blank"))
        self.preview.setObjectName("preview")
        self._3.addWidget(self.preview)
        self.verticalLayout_5.addWidget(self.splitter)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.cardList)
        Dialog.setTabOrder(self.cardList, self.editTemplates)
        Dialog.setTabOrder(self.editTemplates, self.cardQuestion)
        Dialog.setTabOrder(self.cardQuestion, self.flipButton)
        Dialog.setTabOrder(self.flipButton, self.cardAnswer)
        Dialog.setTabOrder(self.cardAnswer, self.alignment)
        Dialog.setTabOrder(self.alignment, self.background)
        Dialog.setTabOrder(self.background, self.typeAnswer)
        Dialog.setTabOrder(self.typeAnswer, self.questionInAnswer)
        Dialog.setTabOrder(self.questionInAnswer, self.allowEmptyAnswer)
        Dialog.setTabOrder(self.allowEmptyAnswer, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.fieldList)
        Dialog.setTabOrder(self.fieldList, self.fieldAdd)
        Dialog.setTabOrder(self.fieldAdd, self.fieldUp)
        Dialog.setTabOrder(self.fieldUp, self.fieldDown)
        Dialog.setTabOrder(self.fieldDown, self.fieldDelete)
        Dialog.setTabOrder(self.fieldDelete, self.fieldName)
        Dialog.setTabOrder(self.fieldName, self.fontFamily)
        Dialog.setTabOrder(self.fontFamily, self.fontSize)
        Dialog.setTabOrder(self.fontSize, self.fontSizeEdit)
        Dialog.setTabOrder(self.fontSizeEdit, self.fontColour)
        Dialog.setTabOrder(self.fontColour, self.fieldUnique)
        Dialog.setTabOrder(self.fieldUnique, self.fieldRequired)
        Dialog.setTabOrder(self.fieldRequired, self.preserveWhitespace)
        Dialog.setTabOrder(self.preserveWhitespace, self.numeric)
        Dialog.setTabOrder(self.numeric, self.rtl)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_("Card Layout"))
        self.editTemplates.setText(_("&Edit"))
        self.label_14.setText(_("Question"))
        self.flipButton.setText(_("Flip"))
        self.label_15.setText(_("Answer"))
        self.label_13.setText(_("Alignment"))
        self.label_16.setText(_("Background"))
        self.questionInAnswer.setText(_("Hide the question when showing answer"))
        self.allowEmptyAnswer.setText(_("Allow the answer to be blank"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _("Card Templates"))
        self.fieldAdd.setText(_("&Add"))
        self.fieldUp.setToolTip(_("Move selected field up"))
        self.fieldUp.setText(_("&Up"))
        self.fieldDown.setToolTip(_("Move selected field down"))
        self.fieldDown.setText(_("Dow&n"))
        self.fieldDelete.setText(_("&Delete"))
        self.label_20.setText(_("Name"))
        self.label_5.setText(_("Font"))
        self.label_6.setText(_("Size"))
        self.label_7.setText(_("Color"))
        self.label.setText(_("Reviewing"))
        self.label_8.setText(_("Editing"))
        self.label_18.setText(_("Options"))
        self.rtl.setText(_("Reverse text direction (RTL)"))
        self.numeric.setText(_("Sort as numbers in browser"))
        self.fieldRequired.setText(_("Prevent empty entries"))
        self.fieldUnique.setText(_("Prevent duplicates"))
        self.preserveWhitespace.setText(_("Preserve whitespace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("Fields"))
        self.previewGroup.setTitle(_("Preview"))

from PyQt4 import QtWebKit
import icons_rc
