# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/deckproperties.ui'
#

#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DeckProperties(object):
    def setupUi(self, DeckProperties):
        DeckProperties.setObjectName("DeckProperties")
        DeckProperties.setWindowModality(QtCore.Qt.ApplicationModal)
        DeckProperties.resize(394,400)
        self.verticalLayout_2 = QtGui.QVBoxLayout(DeckProperties)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.qtabwidget = QtGui.QTabWidget(DeckProperties)
        self.qtabwidget.setObjectName("qtabwidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setGeometry(QtCore.QRect(0,0,378,334))
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15,3,1,1,1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem,0,1,1,1)
        self.newCardsPerDay = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newCardsPerDay.sizePolicy().hasHeightForWidth())
        self.newCardsPerDay.setSizePolicy(sizePolicy)
        self.newCardsPerDay.setObjectName("newCardsPerDay")
        self.gridLayout_3.addWidget(self.newCardsPerDay,0,2,1,1)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11,0,0,1,1)
        self.gridLayout_2.addLayout(self.gridLayout_3,4,1,1,1)
        self.gridLayout_6.addLayout(self.gridLayout_2,0,0,1,1)
        self.newCardOrder = QtGui.QComboBox(self.tab_2)
        self.newCardOrder.setObjectName("newCardOrder")
        self.gridLayout_6.addWidget(self.newCardOrder,1,0,1,1)
        self.newCardScheduling = QtGui.QComboBox(self.tab_2)
        self.newCardScheduling.setObjectName("newCardScheduling")
        self.gridLayout_6.addWidget(self.newCardScheduling,3,0,1,1)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16,8,0,1,1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21,0,0,1,1)
        self.highPriority = QtGui.QLineEdit(self.tab_2)
        self.highPriority.setObjectName("highPriority")
        self.gridLayout_4.addWidget(self.highPriority,0,1,1,1)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17,1,0,1,1)
        self.medPriority = QtGui.QLineEdit(self.tab_2)
        self.medPriority.setObjectName("medPriority")
        self.gridLayout_4.addWidget(self.medPriority,1,1,1,1)
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24,2,0,1,1)
        self.lowPriority = QtGui.QLineEdit(self.tab_2)
        self.lowPriority.setObjectName("lowPriority")
        self.gridLayout_4.addWidget(self.lowPriority,2,1,1,1)
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23,3,0,1,1)
        self.postponing = QtGui.QLineEdit(self.tab_2)
        self.postponing.setObjectName("postponing")
        self.gridLayout_4.addWidget(self.postponing,3,1,1,1)
        self.gridLayout_6.addLayout(self.gridLayout_4,9,0,1,1)
        spacerItem1 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1,10,0,1,1)
        self.revCardOrder = QtGui.QComboBox(self.tab_2)
        self.revCardOrder.setObjectName("revCardOrder")
        self.gridLayout_6.addWidget(self.revCardOrder,4,0,1,1)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2,6,0,1,1)
        spacerItem2 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2,5,0,1,1)
        spacerItem3 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3,7,0,1,1)
        self.qtabwidget.addTab(self.tab_2,"")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setGeometry(QtCore.QRect(0,0,378,334))
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtGui.QLabel(self.tab_5)
        self.label_13.setScaledContents(False)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13,0,0,1,1)
        self.doSync = QtGui.QCheckBox(self.tab_5)
        self.doSync.setObjectName("doSync")
        self.gridLayout.addWidget(self.doSync,1,0,1,1)
        self.label_28 = QtGui.QLabel(self.tab_5)
        self.label_28.setMaximumSize(QtCore.QSize(16777215,40))
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28,6,0,1,1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addSource = QtGui.QPushButton(self.tab_5)
        self.addSource.setAutoDefault(False)
        self.addSource.setObjectName("addSource")
        self.horizontalLayout_3.addWidget(self.addSource)
        self.deleteSource = QtGui.QPushButton(self.tab_5)
        self.deleteSource.setAutoDefault(False)
        self.deleteSource.setObjectName("deleteSource")
        self.horizontalLayout_3.addWidget(self.deleteSource)
        self.gridLayout.addLayout(self.horizontalLayout_3,8,0,1,1)
        self.sourcesTable = QtGui.QTableWidget(self.tab_5)
        self.sourcesTable.setObjectName("sourcesTable")
        self.gridLayout.addWidget(self.sourcesTable,7,0,1,1)
        spacerItem4 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4,3,0,1,1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_18 = QtGui.QLabel(self.tab_5)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.syncName = QtGui.QLineEdit(self.tab_5)
        self.syncName.setEnabled(False)
        self.syncName.setObjectName("syncName")
        self.horizontalLayout_2.addWidget(self.syncName)
        self.gridLayout.addLayout(self.horizontalLayout_2,2,0,1,1)
        self.line_3 = QtGui.QFrame(self.tab_5)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3,4,0,1,1)
        spacerItem5 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5,5,0,1,1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.qtabwidget.addTab(self.tab_5,"")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setGeometry(QtCore.QRect(0,0,378,334))
        self.tab_3.setObjectName("tab_3")
        self.vboxlayout = QtGui.QVBoxLayout(self.tab_3)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.vboxlayout.addWidget(self.label_14)
        self.modelsList = QtGui.QListWidget(self.tab_3)
        self.modelsList.setObjectName("modelsList")
        self.vboxlayout.addWidget(self.modelsList)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.modelsAdd = QtGui.QPushButton(self.tab_3)
        self.modelsAdd.setObjectName("modelsAdd")
        self.hboxlayout.addWidget(self.modelsAdd)
        self.modelsEdit = QtGui.QPushButton(self.tab_3)
        self.modelsEdit.setObjectName("modelsEdit")
        self.hboxlayout.addWidget(self.modelsEdit)
        self.modelsDelete = QtGui.QPushButton(self.tab_3)
        self.modelsDelete.setObjectName("modelsDelete")
        self.hboxlayout.addWidget(self.modelsDelete)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.qtabwidget.addTab(self.tab_3,"")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setGeometry(QtCore.QRect(0,0,378,334))
        self.tab_4.setObjectName("tab_4")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.tab_4)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label_27 = QtGui.QLabel(self.tab_4)
        self.label_27.setObjectName("label_27")
        self.vboxlayout1.addWidget(self.label_27)
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.easyMin = QtGui.QLineEdit(self.tab_4)
        self.easyMin.setObjectName("easyMin")
        self.gridlayout.addWidget(self.easyMin,5,2,1,1)
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setObjectName("label_6")
        self.gridlayout.addWidget(self.label_6,4,1,1,1)
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setObjectName("label_7")
        self.gridlayout.addWidget(self.label_7,5,1,1,1)
        self.midMax = QtGui.QLineEdit(self.tab_4)
        self.midMax.setObjectName("midMax")
        self.gridlayout.addWidget(self.midMax,4,4,1,1)
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4,5,0,1,1)
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName("label_3")
        self.gridlayout.addWidget(self.label_3,4,0,1,1)
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setObjectName("label_10")
        self.gridlayout.addWidget(self.label_10,5,3,1,1)
        self.hardMin = QtGui.QLineEdit(self.tab_4)
        self.hardMin.setObjectName("hardMin")
        self.gridlayout.addWidget(self.hardMin,3,2,1,1)
        self.midMin = QtGui.QLineEdit(self.tab_4)
        self.midMin.setObjectName("midMin")
        self.gridlayout.addWidget(self.midMin,4,2,1,1)
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.gridlayout.addWidget(self.label_8,3,3,1,1)
        self.easyMax = QtGui.QLineEdit(self.tab_4)
        self.easyMax.setObjectName("easyMax")
        self.gridlayout.addWidget(self.easyMax,5,4,1,1)
        self.hardMax = QtGui.QLineEdit(self.tab_4)
        self.hardMax.setObjectName("hardMax")
        self.gridlayout.addWidget(self.hardMax,3,4,1,1)
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setObjectName("label_5")
        self.gridlayout.addWidget(self.label_5,3,1,1,1)
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.gridlayout.addWidget(self.label_9,4,3,1,1)
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2,3,0,1,1)
        self.delay0 = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay0.sizePolicy().hasHeightForWidth())
        self.delay0.setSizePolicy(sizePolicy)
        self.delay0.setObjectName("delay0")
        self.gridlayout.addWidget(self.delay0,0,4,1,1)
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setOpenExternalLinks(True)
        self.label_22.setObjectName("label_22")
        self.gridlayout.addWidget(self.label_22,1,0,1,1)
        self.delay1 = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay1.sizePolicy().hasHeightForWidth())
        self.delay1.setSizePolicy(sizePolicy)
        self.delay1.setObjectName("delay1")
        self.gridlayout.addWidget(self.delay1,1,4,1,1)
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setOpenExternalLinks(True)
        self.label_19.setObjectName("label_19")
        self.gridlayout.addWidget(self.label_19,2,0,1,1)
        self.delay2 = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay2.sizePolicy().hasHeightForWidth())
        self.delay2.setSizePolicy(sizePolicy)
        self.delay2.setObjectName("delay2")
        self.gridlayout.addWidget(self.delay2,2,4,1,1)
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setObjectName("label_20")
        self.gridlayout.addWidget(self.label_20,0,0,1,1)
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label,0,5,1,1)
        self.label_25 = QtGui.QLabel(self.tab_4)
        self.label_25.setObjectName("label_25")
        self.gridlayout.addWidget(self.label_25,1,5,1,1)
        self.label_30 = QtGui.QLabel(self.tab_4)
        self.label_30.setObjectName("label_30")
        self.gridlayout.addWidget(self.label_30,3,5,1,1)
        self.label_31 = QtGui.QLabel(self.tab_4)
        self.label_31.setObjectName("label_31")
        self.gridlayout.addWidget(self.label_31,4,5,1,1)
        self.label_32 = QtGui.QLabel(self.tab_4)
        self.label_32.setObjectName("label_32")
        self.gridlayout.addWidget(self.label_32,5,5,1,1)
        self.vboxlayout1.addLayout(self.gridlayout)
        self.line = QtGui.QFrame(self.tab_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vboxlayout1.addWidget(self.line)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_12 = QtGui.QLabel(self.tab_4)
        self.label_12.setOpenExternalLinks(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12,1,0,1,1)
        spacerItem6 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6,1,1,1,1)
        self.failedCardMax = QtGui.QLineEdit(self.tab_4)
        self.failedCardMax.setObjectName("failedCardMax")
        self.gridLayout_5.addWidget(self.failedCardMax,1,2,1,1)
        self.label_29 = QtGui.QLabel(self.tab_4)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29,3,0,1,1)
        spacerItem7 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7,3,1,1,1)
        self.timeOffset = QtGui.QLineEdit(self.tab_4)
        self.timeOffset.setObjectName("timeOffset")
        self.gridLayout_5.addWidget(self.timeOffset,3,2,1,1)
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setOpenExternalLinks(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26,0,0,1,1)
        spacerItem8 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8,0,1,1,1)
        self.collapse = QtGui.QCheckBox(self.tab_4)
        self.collapse.setObjectName("collapse")
        self.gridLayout_5.addWidget(self.collapse,0,2,1,1)
        self.vboxlayout1.addLayout(self.gridLayout_5)
        spacerItem9 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem9)
        self.qtabwidget.addTab(self.tab_4,"")
        self.verticalLayout_2.addWidget(self.qtabwidget)
        self.buttonBox = QtGui.QDialogButtonBox(DeckProperties)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DeckProperties)
        self.qtabwidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("accepted()"),DeckProperties.accept)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("rejected()"),DeckProperties.reject)
        QtCore.QObject.connect(self.doSync,QtCore.SIGNAL("toggled(bool)"),self.syncName.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DeckProperties)
        DeckProperties.setTabOrder(self.qtabwidget,self.newCardsPerDay)
        DeckProperties.setTabOrder(self.newCardsPerDay,self.newCardOrder)
        DeckProperties.setTabOrder(self.newCardOrder,self.newCardScheduling)
        DeckProperties.setTabOrder(self.newCardScheduling,self.revCardOrder)
        DeckProperties.setTabOrder(self.revCardOrder,self.highPriority)
        DeckProperties.setTabOrder(self.highPriority,self.medPriority)
        DeckProperties.setTabOrder(self.medPriority,self.lowPriority)
        DeckProperties.setTabOrder(self.lowPriority,self.postponing)
        DeckProperties.setTabOrder(self.postponing,self.doSync)
        DeckProperties.setTabOrder(self.doSync,self.syncName)
        DeckProperties.setTabOrder(self.syncName,self.sourcesTable)
        DeckProperties.setTabOrder(self.sourcesTable,self.addSource)
        DeckProperties.setTabOrder(self.addSource,self.deleteSource)
        DeckProperties.setTabOrder(self.deleteSource,self.modelsList)
        DeckProperties.setTabOrder(self.modelsList,self.modelsAdd)
        DeckProperties.setTabOrder(self.modelsAdd,self.modelsEdit)
        DeckProperties.setTabOrder(self.modelsEdit,self.modelsDelete)
        DeckProperties.setTabOrder(self.modelsDelete,self.delay0)
        DeckProperties.setTabOrder(self.delay0,self.delay1)
        DeckProperties.setTabOrder(self.delay1,self.delay2)
        DeckProperties.setTabOrder(self.delay2,self.hardMin)
        DeckProperties.setTabOrder(self.hardMin,self.hardMax)
        DeckProperties.setTabOrder(self.hardMax,self.midMin)
        DeckProperties.setTabOrder(self.midMin,self.midMax)
        DeckProperties.setTabOrder(self.midMax,self.easyMin)
        DeckProperties.setTabOrder(self.easyMin,self.easyMax)
        DeckProperties.setTabOrder(self.easyMax,self.collapse)
        DeckProperties.setTabOrder(self.collapse,self.failedCardMax)
        DeckProperties.setTabOrder(self.failedCardMax,self.timeOffset)
        DeckProperties.setTabOrder(self.timeOffset,self.buttonBox)

    def retranslateUi(self, DeckProperties):
        DeckProperties.setWindowTitle(_("Deck Properties"))
        self.qtabwidget.setWhatsThis(_("<a href=\"http://ichi2.net/anki/wiki/DeckProperties#Synchronization\">Help</a>"))
        self.label_15.setText(_("<h1>Basic Scheduling</h1>"))
        self.label_11.setText(_("<b>Number of new cards per day"))
        self.label_16.setText(_("<h1>Priorities</h1>"))
        self.label_21.setText(_("<b>Very High Priority</b>"))
        self.label_17.setText(_("<b>High Priority</b>"))
        self.label_24.setText(_("<b>Low Priority</b>"))
        self.label_23.setText(_("<b>Suspended</b>"))
        self.qtabwidget.setTabText(self.qtabwidget.indexOf(self.tab_2), _("Scheduling"))
        self.label_13.setWhatsThis(_("label"))
        self.label_13.setText(_("<h1>Synchronisation</h1>"))
        self.doSync.setText(_("Synchronize this deck"))
        self.label_28.setText(_("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:xx-large; font-weight:600;\"><span style=\" font-size:xx-large;\">Sources</span></p></body></html>"))
        self.addSource.setText(_("&Add Source"))
        self.deleteSource.setText(_("&Delete Source"))
        self.sourcesTable.clear()
        self.sourcesTable.setColumnCount(0)
        self.sourcesTable.setRowCount(0)
        self.label_18.setText(_("Name on server: "))
        self.syncName.setWhatsThis(_("option"))
        self.qtabwidget.setTabText(self.qtabwidget.indexOf(self.tab_5), _("Synchronisation"))
        self.label_14.setText(_("<h1>Models</h1>"))
        self.modelsAdd.setText(_("&Add"))
        self.modelsEdit.setText(_("&Edit"))
        self.modelsDelete.setText(_("&Delete"))
        self.qtabwidget.setTabText(self.qtabwidget.indexOf(self.tab_3), _("Models"))
        self.label_27.setText(_("<h1>Advanced Scheduling</h1>"))
        self.label_6.setText(_("Min"))
        self.label_7.setText(_("Min"))
        self.label_4.setText(_("<b>4: Initial Easy Interval</b>"))
        self.label_3.setText(_("<b>3: Initial Good Interval</b>"))
        self.label_10.setText(_("Max"))
        self.label_8.setText(_("Max"))
        self.label_5.setText(_("Min"))
        self.label_9.setText(_("Max"))
        self.label_2.setText(_("<b>2: Initial Hard Interval</b>"))
        self.label_22.setText(_("<b>1: Again (Mature)</b>"))
        self.label_19.setText(_("<b>1: Failure Multiplier</b>"))
        self.label_20.setText(_("<b>1: Again (Young)</b>"))
        self.label.setText(_("mins"))
        self.label_25.setText(_("mins"))
        self.label_30.setText(_("days"))
        self.label_31.setText(_("days"))
        self.label_32.setText(_("days"))
        self.label_12.setText(_("<b>Maximum failed cards</b>"))
        self.label_29.setText(_("<b>New day starts at</b>"))
        self.label_26.setText(_("<b>Show failed cards early</b>"))
        self.qtabwidget.setTabText(self.qtabwidget.indexOf(self.tab_4), _("Advanced"))

