# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/deckproperties.ui'
#

#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DeckProperties(object):
    def setupUi(self, DeckProperties):
        DeckProperties.setObjectName("DeckProperties")
        DeckProperties.setWindowModality(QtCore.Qt.ApplicationModal)
        DeckProperties.resize(383, 452)
        self.verticalLayout_2 = QtGui.QVBoxLayout(DeckProperties)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.qtabwidget = QtGui.QTabWidget(DeckProperties)
        self.qtabwidget.setObjectName("qtabwidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 5, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.highPriority = QtGui.QLineEdit(self.tab_2)
        self.highPriority.setObjectName("highPriority")
        self.gridLayout_4.addWidget(self.highPriority, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.medPriority = QtGui.QLineEdit(self.tab_2)
        self.medPriority.setObjectName("medPriority")
        self.gridLayout_4.addWidget(self.medPriority, 1, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 2, 0, 1, 1)
        self.lowPriority = QtGui.QLineEdit(self.tab_2)
        self.lowPriority.setObjectName("lowPriority")
        self.gridLayout_4.addWidget(self.lowPriority, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 6, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 7, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 3, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.modelsList = QtGui.QListWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelsList.sizePolicy().hasHeightForWidth())
        self.modelsList.setSizePolicy(sizePolicy)
        self.modelsList.setObjectName("modelsList")
        self.gridLayout_2.addWidget(self.modelsList, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.modelsAdd = QtGui.QPushButton(self.tab_2)
        self.modelsAdd.setAutoDefault(False)
        self.modelsAdd.setObjectName("modelsAdd")
        self.verticalLayout_3.addWidget(self.modelsAdd)
        self.modelsEdit = QtGui.QPushButton(self.tab_2)
        self.modelsEdit.setAutoDefault(False)
        self.modelsEdit.setObjectName("modelsEdit")
        self.verticalLayout_3.addWidget(self.modelsEdit)
        self.modelsDelete = QtGui.QPushButton(self.tab_2)
        self.modelsDelete.setAutoDefault(False)
        self.modelsDelete.setObjectName("modelsDelete")
        self.verticalLayout_3.addWidget(self.modelsDelete)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 4, 0, 1, 1)
        self.doSync = QtGui.QCheckBox(self.tab_2)
        self.doSync.setObjectName("doSync")
        self.gridLayout_6.addWidget(self.doSync, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setScaledContents(False)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.mediaURL = QtGui.QLineEdit(self.tab_2)
        self.mediaURL.setObjectName("mediaURL")
        self.gridLayout_3.addWidget(self.mediaURL, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.qtabwidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.latexHeader = QtGui.QTextEdit(self.tab)
        self.latexHeader.setTabChangesFocus(True)
        self.latexHeader.setObjectName("latexHeader")
        self.verticalLayout.addWidget(self.latexHeader)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.latexFooter = QtGui.QTextEdit(self.tab)
        self.latexFooter.setTabChangesFocus(True)
        self.latexFooter.setObjectName("latexFooter")
        self.verticalLayout.addWidget(self.latexFooter)
        self.qtabwidget.addTab(self.tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.vboxlayout = QtGui.QVBoxLayout(self.tab_4)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.easyMin = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.easyMin.sizePolicy().hasHeightForWidth())
        self.easyMin.setSizePolicy(sizePolicy)
        self.easyMin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.easyMin.setObjectName("easyMin")
        self.gridlayout.addWidget(self.easyMin, 6, 2, 1, 1)
        self.midMax = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midMax.sizePolicy().hasHeightForWidth())
        self.midMax.setSizePolicy(sizePolicy)
        self.midMax.setMaximumSize(QtCore.QSize(50, 16777215))
        self.midMax.setObjectName("midMax")
        self.gridlayout.addWidget(self.midMax, 5, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName("label_3")
        self.gridlayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridlayout.addWidget(self.label_10, 6, 3, 1, 1)
        self.hardMin = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hardMin.sizePolicy().hasHeightForWidth())
        self.hardMin.setSizePolicy(sizePolicy)
        self.hardMin.setMinimumSize(QtCore.QSize(50, 0))
        self.hardMin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.hardMin.setObjectName("hardMin")
        self.gridlayout.addWidget(self.hardMin, 4, 2, 1, 1)
        self.midMin = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midMin.sizePolicy().hasHeightForWidth())
        self.midMin.setSizePolicy(sizePolicy)
        self.midMin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.midMin.setObjectName("midMin")
        self.gridlayout.addWidget(self.midMin, 5, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridlayout.addWidget(self.label_8, 4, 3, 1, 1)
        self.easyMax = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.easyMax.sizePolicy().hasHeightForWidth())
        self.easyMax.setSizePolicy(sizePolicy)
        self.easyMax.setMaximumSize(QtCore.QSize(50, 16777215))
        self.easyMax.setObjectName("easyMax")
        self.gridlayout.addWidget(self.easyMax, 6, 4, 1, 1)
        self.hardMax = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hardMax.sizePolicy().hasHeightForWidth())
        self.hardMax.setSizePolicy(sizePolicy)
        self.hardMax.setMinimumSize(QtCore.QSize(50, 0))
        self.hardMax.setMaximumSize(QtCore.QSize(50, 16777215))
        self.hardMax.setObjectName("hardMax")
        self.gridlayout.addWidget(self.hardMax, 4, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridlayout.addWidget(self.label_9, 5, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setObjectName("label_20")
        self.gridlayout.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_4)
        self.label_30.setObjectName("label_30")
        self.gridlayout.addWidget(self.label_30, 4, 5, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_4)
        self.label_31.setObjectName("label_31")
        self.gridlayout.addWidget(self.label_31, 5, 5, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_4)
        self.label_32.setObjectName("label_32")
        self.gridlayout.addWidget(self.label_32, 6, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem2, 4, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setOpenExternalLinks(True)
        self.label_19.setObjectName("label_19")
        self.gridlayout.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setOpenExternalLinks(True)
        self.label_22.setObjectName("label_22")
        self.gridlayout.addWidget(self.label_22, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridlayout.addWidget(self.line_2, 3, 0, 1, 6)
        self.delay0 = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay0.sizePolicy().hasHeightForWidth())
        self.delay0.setSizePolicy(sizePolicy)
        self.delay0.setMinimumSize(QtCore.QSize(50, 0))
        self.delay0.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delay0.setObjectName("delay0")
        self.gridlayout.addWidget(self.delay0, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 3, 1, 2)
        self.delay2 = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay2.sizePolicy().hasHeightForWidth())
        self.delay2.setSizePolicy(sizePolicy)
        self.delay2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delay2.setObjectName("delay2")
        self.gridlayout.addWidget(self.delay2, 1, 2, 1, 1)
        self.delay1 = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay1.sizePolicy().hasHeightForWidth())
        self.delay1.setSizePolicy(sizePolicy)
        self.delay1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delay1.setObjectName("delay1")
        self.gridlayout.addWidget(self.delay1, 2, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_4)
        self.label_25.setObjectName("label_25")
        self.gridlayout.addWidget(self.label_25, 2, 3, 1, 2)
        self.line = QtGui.QFrame(self.tab_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridlayout.addWidget(self.line, 7, 0, 1, 6)
        self.line_3 = QtGui.QFrame(self.tab_4)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridlayout.addWidget(self.line_3, 12, 0, 1, 6)
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setOpenExternalLinks(True)
        self.label_26.setObjectName("label_26")
        self.gridlayout.addWidget(self.label_26, 13, 0, 1, 1)
        self.collapse = QtGui.QCheckBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collapse.sizePolicy().hasHeightForWidth())
        self.collapse.setSizePolicy(sizePolicy)
        self.collapse.setText("")
        self.collapse.setObjectName("collapse")
        self.gridlayout.addWidget(self.collapse, 13, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setObjectName("label_23")
        self.gridlayout.addWidget(self.label_23, 15, 0, 1, 1)
        self.perDay = QtGui.QCheckBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perDay.sizePolicy().hasHeightForWidth())
        self.perDay.setSizePolicy(sizePolicy)
        self.perDay.setText("")
        self.perDay.setObjectName("perDay")
        self.gridlayout.addWidget(self.perDay, 15, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.gridlayout.addWidget(self.label_15, 8, 0, 1, 1)
        self.leechFails = QtGui.QSpinBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leechFails.sizePolicy().hasHeightForWidth())
        self.leechFails.setSizePolicy(sizePolicy)
        self.leechFails.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leechFails.setObjectName("leechFails")
        self.gridlayout.addWidget(self.leechFails, 8, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_4)
        self.label_29.setObjectName("label_29")
        self.gridlayout.addWidget(self.label_29, 9, 0, 1, 1)
        self.timeOffset = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeOffset.sizePolicy().hasHeightForWidth())
        self.timeOffset.setSizePolicy(sizePolicy)
        self.timeOffset.setMaximumSize(QtCore.QSize(50, 16777215))
        self.timeOffset.setObjectName("timeOffset")
        self.gridlayout.addWidget(self.timeOffset, 9, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_4)
        self.label_12.setObjectName("label_12")
        self.gridlayout.addWidget(self.label_12, 10, 0, 1, 1)
        self.newSpacing = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newSpacing.sizePolicy().hasHeightForWidth())
        self.newSpacing.setSizePolicy(sizePolicy)
        self.newSpacing.setMaximumSize(QtCore.QSize(50, 16777215))
        self.newSpacing.setObjectName("newSpacing")
        self.gridlayout.addWidget(self.newSpacing, 10, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab_4)
        self.label_27.setObjectName("label_27")
        self.gridlayout.addWidget(self.label_27, 10, 3, 1, 2)
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setObjectName("label_11")
        self.gridlayout.addWidget(self.label_11, 14, 0, 1, 1)
        self.suspendLeeches = QtGui.QCheckBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.suspendLeeches.sizePolicy().hasHeightForWidth())
        self.suspendLeeches.setSizePolicy(sizePolicy)
        self.suspendLeeches.setText("")
        self.suspendLeeches.setObjectName("suspendLeeches")
        self.gridlayout.addWidget(self.suspendLeeches, 14, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_4)
        self.label_33.setObjectName("label_33")
        self.gridlayout.addWidget(self.label_33, 1, 3, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.gridlayout.addWidget(self.label_34, 9, 3, 1, 3)
        self.label_35 = QtGui.QLabel(self.tab_4)
        self.label_35.setObjectName("label_35")
        self.gridlayout.addWidget(self.label_35, 8, 3, 1, 2)
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setObjectName("label_18")
        self.gridlayout.addWidget(self.label_18, 11, 0, 1, 1)
        self.revSpacing = QtGui.QLineEdit(self.tab_4)
        self.revSpacing.setObjectName("revSpacing")
        self.gridlayout.addWidget(self.revSpacing, 11, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_4)
        self.label_28.setObjectName("label_28")
        self.gridlayout.addWidget(self.label_28, 11, 3, 1, 2)
        self.vboxlayout.addLayout(self.gridlayout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem3)
        self.qtabwidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.qtabwidget)
        self.buttonBox = QtGui.QDialogButtonBox(DeckProperties)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DeckProperties)
        self.qtabwidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), DeckProperties.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DeckProperties.reject)
        QtCore.QMetaObject.connectSlotsByName(DeckProperties)
        DeckProperties.setTabOrder(self.qtabwidget, self.doSync)
        DeckProperties.setTabOrder(self.doSync, self.mediaURL)
        DeckProperties.setTabOrder(self.mediaURL, self.modelsList)
        DeckProperties.setTabOrder(self.modelsList, self.modelsAdd)
        DeckProperties.setTabOrder(self.modelsAdd, self.modelsEdit)
        DeckProperties.setTabOrder(self.modelsEdit, self.modelsDelete)
        DeckProperties.setTabOrder(self.modelsDelete, self.highPriority)
        DeckProperties.setTabOrder(self.highPriority, self.medPriority)
        DeckProperties.setTabOrder(self.medPriority, self.lowPriority)
        DeckProperties.setTabOrder(self.lowPriority, self.buttonBox)
        DeckProperties.setTabOrder(self.buttonBox, self.latexHeader)
        DeckProperties.setTabOrder(self.latexHeader, self.latexFooter)
        DeckProperties.setTabOrder(self.latexFooter, self.delay0)
        DeckProperties.setTabOrder(self.delay0, self.delay2)
        DeckProperties.setTabOrder(self.delay2, self.delay1)
        DeckProperties.setTabOrder(self.delay1, self.hardMin)
        DeckProperties.setTabOrder(self.hardMin, self.hardMax)
        DeckProperties.setTabOrder(self.hardMax, self.midMin)
        DeckProperties.setTabOrder(self.midMin, self.midMax)
        DeckProperties.setTabOrder(self.midMax, self.easyMin)
        DeckProperties.setTabOrder(self.easyMin, self.easyMax)
        DeckProperties.setTabOrder(self.easyMax, self.leechFails)
        DeckProperties.setTabOrder(self.leechFails, self.timeOffset)
        DeckProperties.setTabOrder(self.timeOffset, self.newSpacing)
        DeckProperties.setTabOrder(self.newSpacing, self.revSpacing)
        DeckProperties.setTabOrder(self.revSpacing, self.collapse)
        DeckProperties.setTabOrder(self.collapse, self.suspendLeeches)
        DeckProperties.setTabOrder(self.suspendLeeches, self.perDay)

    def retranslateUi(self, DeckProperties):
        DeckProperties.setWindowTitle(_("Deck Properties"))
        self.qtabwidget.setWhatsThis(_("<a href=\"http://ichi2.net/anki/wiki/DeckProperties#Synchronization\">Help</a>"))
        self.label_16.setText(_("<b>Priorities</b>"))
        self.label_21.setText(_("Very high priority"))
        self.label_17.setText(_("High priority"))
        self.label_24.setText(_("Low priority"))
        self.label_14.setText(_("<b>Models</b>"))
        self.modelsAdd.setText(_("&Add"))
        self.modelsEdit.setText(_("&Edit"))
        self.modelsDelete.setText(_("&Delete"))
        self.doSync.setText(_("Synchronize this deck with AnkiWeb"))
        self.label_13.setWhatsThis(_("label"))
        self.label_13.setText(_("<b>Synchronization</b>"))
        self.label_5.setText(_("Media URL"))
        self.qtabwidget.setTabText(self.qtabwidget.indexOf(self.tab_2), _("Basic"))
        self.label_6.setText(_("Header"))
        self.label_7.setText(_("Footer"))
        self.qtabwidget.setTabText(self.qtabwidget.indexOf(self.tab), _("LaTeX"))
        self.label_4.setText(_("Initial button 4 interval"))
        self.label_3.setText(_("Initial button 3 interval"))
        self.label_10.setText(_("~"))
        self.label_8.setText(_("~"))
        self.label_9.setText(_("~"))
        self.label_2.setText(_("Initial button 2 interval"))
        self.label_20.setText(_("Button 1 delay"))
        self.label_30.setText(_("days"))
        self.label_31.setText(_("days"))
        self.label_32.setText(_("days"))
        self.label_19.setText(_("Button 1 multiplier"))
        self.label_22.setText(_("Mature bonus"))
        self.label.setText(_("minutes"))
        self.label_25.setText(_("days"))
        self.label_26.setText(_("Show failed cards early"))
        self.label_23.setText(_("Per-day scheduling"))
        self.label_15.setText(_("Leech threshold"))
        self.label_29.setText(_("Shift midnight by"))
        self.label_12.setText(_("Sibling delay (new cards)"))
        self.label_27.setText(_("minutes"))
        self.label_11.setText(_("Suspend leeches"))
        self.label_33.setText(_("%"))
        self.label_34.setText(_("hours"))
        self.label_35.setText(_("failures"))
        self.label_18.setText(_("Sibling delay (reviews)"))
        self.label_28.setText(_("%"))
        self.qtabwidget.setTabText(self.qtabwidget.indexOf(self.tab_4), _("Advanced"))

