# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/displayproperties.ui'
#

#      by: PyQt4 UI code generator 4.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DisplayProperties(object):
    def setupUi(self, DisplayProperties):
        DisplayProperties.setObjectName("DisplayProperties")
        DisplayProperties.resize(818, 427)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DisplayProperties.sizePolicy().hasHeightForWidth())
        DisplayProperties.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/fonts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DisplayProperties.setWindowIcon(icon)
        self._3 = QtGui.QVBoxLayout(DisplayProperties)
        self._3.setSpacing(6)
        self._3.setMargin(9)
        self._3.setObjectName("_3")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(12)
        self.gridlayout.setObjectName("gridlayout")
        self.frame = QtGui.QFrame(DisplayProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(360, 0))
        self.frame.setMaximumSize(QtCore.QSize(360, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.vboxlayout = QtGui.QVBoxLayout(self.frame)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setSpacing(7)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.modelArea = QtGui.QWidget(self.frame)
        self.modelArea.setObjectName("modelArea")
        self.vboxlayout1.addWidget(self.modelArea)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.vboxlayout1.addLayout(self.gridlayout1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.cardList = QtGui.QComboBox(self.tab)
        self.cardList.setObjectName("cardList")
        self.horizontalLayout_2.addWidget(self.cardList)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self._2 = QtGui.QGridLayout()
        self._2.setMargin(0)
        self._2.setSpacing(5)
        self._2.setObjectName("_2")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self._2.addWidget(self.label_6, 0, 0, 1, 1)
        self.answerColour = QtGui.QPushButton(self.tab)
        self.answerColour.setAutoDefault(False)
        self.answerColour.setObjectName("answerColour")
        self._2.addWidget(self.answerColour, 6, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self._2.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self._2.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self._2.addWidget(self.label_9, 4, 0, 1, 1)
        self.answerFont = QtGui.QFontComboBox(self.tab)
        self.answerFont.setObjectName("answerFont")
        self._2.addWidget(self.answerFont, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self._2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self._2.addWidget(self.label_7, 1, 0, 1, 1)
        self.questionSize = QtGui.QSpinBox(self.tab)
        self.questionSize.setMaximum(300)
        self.questionSize.setObjectName("questionSize")
        self._2.addWidget(self.questionSize, 1, 1, 1, 1)
        self.questionFont = QtGui.QFontComboBox(self.tab)
        self.questionFont.setObjectName("questionFont")
        self._2.addWidget(self.questionFont, 0, 1, 1, 1)
        self.questionColour = QtGui.QPushButton(self.tab)
        self.questionColour.setAutoDefault(False)
        self.questionColour.setObjectName("questionColour")
        self._2.addWidget(self.questionColour, 2, 1, 1, 1)
        self.answerSize = QtGui.QSpinBox(self.tab)
        self.answerSize.setMaximum(300)
        self.answerSize.setObjectName("answerSize")
        self._2.addWidget(self.answerSize, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self._2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self._2.addWidget(self.label_12, 7, 0, 1, 1)
        self.questionAlign = QtGui.QComboBox(self.tab)
        self.questionAlign.setObjectName("questionAlign")
        self._2.addWidget(self.questionAlign, 3, 1, 1, 1)
        self.answerAlign = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answerAlign.sizePolicy().hasHeightForWidth())
        self.answerAlign.setSizePolicy(sizePolicy)
        self.answerAlign.setObjectName("answerAlign")
        self._2.addWidget(self.answerAlign, 7, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self._2.addWidget(self.label_5, 8, 0, 1, 1)
        self.backgroundColour = QtGui.QPushButton(self.tab)
        self.backgroundColour.setAutoDefault(False)
        self.backgroundColour.setObjectName("backgroundColour")
        self._2.addWidget(self.backgroundColour, 8, 1, 1, 1)
        self.verticalLayout.addLayout(self._2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fieldList = QtGui.QListWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldList.sizePolicy().hasHeightForWidth())
        self.fieldList.setSizePolicy(sizePolicy)
        self.fieldList.setMinimumSize(QtCore.QSize(0, 60))
        self.fieldList.setObjectName("fieldList")
        self.verticalLayout_2.addWidget(self.fieldList)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self._4 = QtGui.QGridLayout()
        self._4.setMargin(0)
        self._4.setSpacing(5)
        self._4.setObjectName("_4")
        self.useSize = QtGui.QCheckBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useSize.sizePolicy().hasHeightForWidth())
        self.useSize.setSizePolicy(sizePolicy)
        self.useSize.setMinimumSize(QtCore.QSize(0, 25))
        self.useSize.setObjectName("useSize")
        self._4.addWidget(self.useSize, 1, 0, 1, 1)
        self.fontFamily = QtGui.QFontComboBox(self.tab_2)
        self.fontFamily.setMinimumSize(QtCore.QSize(0, 25))
        self.fontFamily.setObjectName("fontFamily")
        self._4.addWidget(self.fontFamily, 0, 1, 1, 1)
        self.useFamily = QtGui.QCheckBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useFamily.sizePolicy().hasHeightForWidth())
        self.useFamily.setSizePolicy(sizePolicy)
        self.useFamily.setMinimumSize(QtCore.QSize(0, 25))
        self.useFamily.setObjectName("useFamily")
        self._4.addWidget(self.useFamily, 0, 0, 1, 1)
        self.fontSize = QtGui.QSpinBox(self.tab_2)
        self.fontSize.setMinimum(5)
        self.fontSize.setMaximum(300)
        self.fontSize.setProperty("value", QtCore.QVariant(14))
        self.fontSize.setObjectName("fontSize")
        self._4.addWidget(self.fontSize, 1, 1, 1, 1)
        self.useColour = QtGui.QCheckBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useColour.sizePolicy().hasHeightForWidth())
        self.useColour.setSizePolicy(sizePolicy)
        self.useColour.setMinimumSize(QtCore.QSize(0, 25))
        self.useColour.setObjectName("useColour")
        self._4.addWidget(self.useColour, 2, 0, 1, 1)
        self.fontColour = QtGui.QPushButton(self.tab_2)
        self.fontColour.setAutoFillBackground(True)
        self.fontColour.setAutoDefault(False)
        self.fontColour.setObjectName("fontColour")
        self._4.addWidget(self.fontColour, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self._4)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self._5 = QtGui.QGridLayout()
        self._5.setMargin(0)
        self._5.setSpacing(5)
        self._5.setObjectName("_5")
        self.fontSizeEdit = QtGui.QSpinBox(self.tab_2)
        self.fontSizeEdit.setMinimum(5)
        self.fontSizeEdit.setMaximum(300)
        self.fontSizeEdit.setObjectName("fontSizeEdit")
        self._5.addWidget(self.fontSizeEdit, 1, 1, 1, 1)
        self.useSizeEdit = QtGui.QCheckBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useSizeEdit.sizePolicy().hasHeightForWidth())
        self.useSizeEdit.setSizePolicy(sizePolicy)
        self.useSizeEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.useSizeEdit.setObjectName("useSizeEdit")
        self._5.addWidget(self.useSizeEdit, 1, 0, 1, 1)
        self.fontFamilyEdit = QtGui.QFontComboBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontFamilyEdit.sizePolicy().hasHeightForWidth())
        self.fontFamilyEdit.setSizePolicy(sizePolicy)
        self.fontFamilyEdit.setObjectName("fontFamilyEdit")
        self._5.addWidget(self.fontFamilyEdit, 0, 1, 1, 1)
        self.useFamilyEdit = QtGui.QCheckBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useFamilyEdit.sizePolicy().hasHeightForWidth())
        self.useFamilyEdit.setSizePolicy(sizePolicy)
        self.useFamilyEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.useFamilyEdit.setObjectName("useFamilyEdit")
        self._5.addWidget(self.useFamilyEdit, 0, 0, 1, 1)
        self.rtl = QtGui.QCheckBox(self.tab_2)
        self.rtl.setObjectName("rtl")
        self._5.addWidget(self.rtl, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self._5)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.helpButton = QtGui.QPushButton(self.frame)
        self.helpButton.setAutoDefault(False)
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout.addWidget(self.helpButton)
        self.preview = QtGui.QPushButton(self.frame)
        self.preview.setCheckable(True)
        self.preview.setAutoDefault(False)
        self.preview.setObjectName("preview")
        self.horizontalLayout.addWidget(self.preview)
        self.closeButton = QtGui.QPushButton(self.frame)
        self.closeButton.setAutoDefault(False)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.vboxlayout1.addLayout(self.verticalLayout_3)
        self.vboxlayout.addLayout(self.vboxlayout1)
        self.gridlayout.addWidget(self.frame, 0, 0, 1, 1)
        self.previewGroup = QtGui.QGroupBox(DisplayProperties)
        self.previewGroup.setObjectName("previewGroup")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.previewGroup)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setMargin(6)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.question = QtGui.QTextEdit(self.previewGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question.sizePolicy().hasHeightForWidth())
        self.question.setSizePolicy(sizePolicy)
        self.question.setReadOnly(True)
        self.question.setObjectName("question")
        self.vboxlayout2.addWidget(self.question)
        self.answer = QtGui.QTextEdit(self.previewGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer.sizePolicy().hasHeightForWidth())
        self.answer.setSizePolicy(sizePolicy)
        self.answer.setReadOnly(True)
        self.answer.setObjectName("answer")
        self.vboxlayout2.addWidget(self.answer)
        self.gridlayout.addWidget(self.previewGroup, 0, 1, 1, 1)
        self._3.addLayout(self.gridlayout)

        self.retranslateUi(DisplayProperties)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL("clicked()"), DisplayProperties.reject)
        QtCore.QObject.connect(self.useFamily, QtCore.SIGNAL("toggled(bool)"), self.fontFamily.setEnabled)
        QtCore.QObject.connect(self.useSize, QtCore.SIGNAL("toggled(bool)"), self.fontSize.setEnabled)
        QtCore.QObject.connect(self.useColour, QtCore.SIGNAL("toggled(bool)"), self.fontColour.setEnabled)
        QtCore.QObject.connect(self.useFamilyEdit, QtCore.SIGNAL("toggled(bool)"), self.fontFamilyEdit.setEnabled)
        QtCore.QObject.connect(self.useSizeEdit, QtCore.SIGNAL("toggled(bool)"), self.fontSizeEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DisplayProperties)
        DisplayProperties.setTabOrder(self.tabWidget, self.cardList)
        DisplayProperties.setTabOrder(self.cardList, self.questionFont)
        DisplayProperties.setTabOrder(self.questionFont, self.questionSize)
        DisplayProperties.setTabOrder(self.questionSize, self.questionColour)
        DisplayProperties.setTabOrder(self.questionColour, self.questionAlign)
        DisplayProperties.setTabOrder(self.questionAlign, self.answerFont)
        DisplayProperties.setTabOrder(self.answerFont, self.answerSize)
        DisplayProperties.setTabOrder(self.answerSize, self.answerColour)
        DisplayProperties.setTabOrder(self.answerColour, self.answerAlign)
        DisplayProperties.setTabOrder(self.answerAlign, self.backgroundColour)
        DisplayProperties.setTabOrder(self.backgroundColour, self.fieldList)
        DisplayProperties.setTabOrder(self.fieldList, self.useFamily)
        DisplayProperties.setTabOrder(self.useFamily, self.fontFamily)
        DisplayProperties.setTabOrder(self.fontFamily, self.useSize)
        DisplayProperties.setTabOrder(self.useSize, self.fontSize)
        DisplayProperties.setTabOrder(self.fontSize, self.useColour)
        DisplayProperties.setTabOrder(self.useColour, self.fontColour)
        DisplayProperties.setTabOrder(self.fontColour, self.useFamilyEdit)
        DisplayProperties.setTabOrder(self.useFamilyEdit, self.fontFamilyEdit)
        DisplayProperties.setTabOrder(self.fontFamilyEdit, self.useSizeEdit)
        DisplayProperties.setTabOrder(self.useSizeEdit, self.fontSizeEdit)
        DisplayProperties.setTabOrder(self.fontSizeEdit, self.rtl)
        DisplayProperties.setTabOrder(self.rtl, self.helpButton)
        DisplayProperties.setTabOrder(self.helpButton, self.preview)
        DisplayProperties.setTabOrder(self.preview, self.closeButton)
        DisplayProperties.setTabOrder(self.closeButton, self.question)
        DisplayProperties.setTabOrder(self.question, self.answer)

    def retranslateUi(self, DisplayProperties):
        DisplayProperties.setWindowTitle(_("Fonts & Colours"))
        self.label_3.setText(_("Card:"))
        self.label_6.setText(_("Question font"))
        self.label_10.setText(_("Answer size"))
        self.label_11.setText(_("Answer colour"))
        self.label_9.setText(_("Answer font"))
        self.label_4.setText(_("Question alignment"))
        self.label_7.setText(_("Question size"))
        self.label_8.setText(_("Question colour"))
        self.label_12.setText(_("Answer alignment"))
        self.label_5.setText(_("Background colour"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _("Cards"))
        self.label.setText(_(" <b>When reviewing and editing:</b>"))
        self.useSize.setText(_("Use custom size"))
        self.useFamily.setText(_("Use custom font"))
        self.useColour.setText(_("Use custom colour"))
        self.label_2.setText(_(" <b>When editing (overrides above):</b>"))
        self.useSizeEdit.setText(_("Use custom size"))
        self.useFamilyEdit.setText(_("Use custom font"))
        self.rtl.setText(_("Reverse text (RTL)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("Fields"))
        self.helpButton.setText(_("Help"))
        self.preview.setText(_("Show preview"))
        self.closeButton.setText(_("Close"))
        self.previewGroup.setTitle(_("Preview"))

import icons_rc
