# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/importing.ui'
#

#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ImportDialog(object):
    def setupUi(self, ImportDialog):
        ImportDialog.setObjectName("ImportDialog")
        ImportDialog.resize(527, 430)
        self.vboxlayout = QtGui.QVBoxLayout(ImportDialog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupBox = QtGui.QGroupBox(ImportDialog)
        self.groupBox.setObjectName("groupBox")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(9)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.autoDetect = QtGui.QPushButton(self.groupBox)
        self.autoDetect.setObjectName("autoDetect")
        self.vboxlayout1.addWidget(self.autoDetect)
        self.modelArea = QtGui.QWidget(self.groupBox)
        self.modelArea.setObjectName("modelArea")
        self.vboxlayout1.addWidget(self.modelArea)
        self.vboxlayout.addWidget(self.groupBox)
        self.mappingGroup = QtGui.QGroupBox(ImportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mappingGroup.sizePolicy().hasHeightForWidth())
        self.mappingGroup.setSizePolicy(sizePolicy)
        self.mappingGroup.setObjectName("mappingGroup")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mappingGroup)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setMargin(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.importButton = QtGui.QPushButton(self.mappingGroup)
        self.importButton.setObjectName("importButton")
        self.verticalLayout.addWidget(self.importButton)
        self.updateButton = QtGui.QPushButton(self.mappingGroup)
        self.updateButton.setObjectName("updateButton")
        self.verticalLayout.addWidget(self.updateButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.mappingArea = QtGui.QScrollArea(self.mappingGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mappingArea.sizePolicy().hasHeightForWidth())
        self.mappingArea.setSizePolicy(sizePolicy)
        self.mappingArea.setMinimumSize(QtCore.QSize(400, 150))
        self.mappingArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.mappingArea.setWidgetResizable(True)
        self.mappingArea.setObjectName("mappingArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.mappingArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 400, 150))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.mappingArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.mappingArea, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.vboxlayout.addWidget(self.mappingGroup)
        self.groupBox_2 = QtGui.QGroupBox(ImportDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setMargin(9)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.status = QtGui.QTextEdit(self.groupBox_2)
        self.status.setReadOnly(True)
        self.status.setObjectName("status")
        self.vboxlayout2.addWidget(self.status)
        self.vboxlayout.addWidget(self.groupBox_2)
        self.buttonBox = QtGui.QDialogButtonBox(ImportDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(ImportDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ImportDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ImportDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ImportDialog)
        ImportDialog.setTabOrder(self.autoDetect, self.importButton)
        ImportDialog.setTabOrder(self.importButton, self.updateButton)
        ImportDialog.setTabOrder(self.updateButton, self.status)
        ImportDialog.setTabOrder(self.status, self.buttonBox)

    def retranslateUi(self, ImportDialog):
        ImportDialog.setWindowTitle(_("Import"))
        self.groupBox.setTitle(_("Import options"))
        self.autoDetect.setText(_("Auto-detect file format"))
        self.mappingGroup.setTitle(_("Field mapping"))
        self.importButton.setText(_("&Import"))
        self.updateButton.setText(_("&Update"))
        self.groupBox_2.setTitle(_("Status"))

