# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/main.ui'
#

#      by: PyQt4 UI code generator 4.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 563)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/anki.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setSpacing(0)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.mainTextFrame = QtGui.QFrame(self.centralwidget)
        self.mainTextFrame.setAutoFillBackground(True)
        self.mainTextFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.mainTextFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mainTextFrame.setObjectName("mainTextFrame")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.mainTextFrame)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setMargin(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.noticeFrame = QtGui.QFrame(self.mainTextFrame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.noticeFrame.setPalette(palette)
        self.noticeFrame.setAutoFillBackground(True)
        self.noticeFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.noticeFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.noticeFrame.setObjectName("noticeFrame")
        self.gridLayout = QtGui.QGridLayout(self.noticeFrame)
        self.gridLayout.setContentsMargins(12, 8, -1, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.noticeLabel = QtGui.QLabel(self.noticeFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noticeLabel.sizePolicy().hasHeightForWidth())
        self.noticeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.noticeLabel.setFont(font)
        self.noticeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.noticeLabel.setWordWrap(True)
        self.noticeLabel.setOpenExternalLinks(True)
        self.noticeLabel.setObjectName("noticeLabel")
        self.gridLayout.addWidget(self.noticeLabel, 0, 0, 1, 1)
        self.noticeButton = QtGui.QPushButton(self.noticeFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noticeButton.sizePolicy().hasHeightForWidth())
        self.noticeButton.setSizePolicy(sizePolicy)
        self.noticeButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.noticeButton.setObjectName("noticeButton")
        self.gridLayout.addWidget(self.noticeButton, 0, 1, 1, 1)
        self.verticalLayout_18.addWidget(self.noticeFrame)
        self.mainStack = QtGui.QStackedWidget(self.mainTextFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.mainStack.sizePolicy().hasHeightForWidth())
        self.mainStack.setSizePolicy(sizePolicy)
        self.mainStack.setObjectName("mainStack")
        self.blankPage = QtGui.QWidget()
        self.blankPage.setObjectName("blankPage")
        self.mainStack.addWidget(self.blankPage)
        self.welcomePage = QtGui.QWidget()
        self.welcomePage.setObjectName("welcomePage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.welcomePage)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtGui.QFrame(self.welcomePage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.welcomeText = QtGui.QTextBrowser(self.frame)
        self.welcomeText.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.welcomeText.setFrameShape(QtGui.QFrame.NoFrame)
        self.welcomeText.setObjectName("welcomeText")
        self.verticalLayout_17.addWidget(self.welcomeText)
        self.verticalLayout_5.addWidget(self.frame)
        self.mainStack.addWidget(self.welcomePage)
        self.editPage = QtGui.QWidget()
        self.editPage.setObjectName("editPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.editPage)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fieldsArea = QtGui.QWidget(self.editPage)
        self.fieldsArea.setObjectName("fieldsArea")
        self.verticalLayout_2.addWidget(self.fieldsArea)
        self.saveEditorButton = QtGui.QPushButton(self.editPage)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/go-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveEditorButton.setIcon(icon1)
        self.saveEditorButton.setIconSize(QtCore.QSize(16, 16))
        self.saveEditorButton.setObjectName("saveEditorButton")
        self.verticalLayout_2.addWidget(self.saveEditorButton)
        self.mainStack.addWidget(self.editPage)
        self.optionsPage = QtGui.QWidget()
        self.optionsPage.setObjectName("optionsPage")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.optionsPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtGui.QSpacerItem(20, 38, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.studyOptionsFrame = QtGui.QFrame(self.optionsPage)
        self.studyOptionsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.studyOptionsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.studyOptionsFrame.setObjectName("studyOptionsFrame")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.studyOptionsFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setMargin(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.optionsLabel = QtGui.QLabel(self.studyOptionsFrame)
        self.optionsLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.optionsLabel.setObjectName("optionsLabel")
        self.verticalLayout_11.addWidget(self.optionsLabel)
        spacerItem2 = QtGui.QSpacerItem(20, 6, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem2)
        self.line_2 = QtGui.QFrame(self.studyOptionsFrame)
        self.line_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_11.addWidget(self.line_2)
        self.studyOptionsLayout1 = QtGui.QGridLayout()
        self.studyOptionsLayout1.setContentsMargins(2, 6, -1, -1)
        self.studyOptionsLayout1.setHorizontalSpacing(0)
        self.studyOptionsLayout1.setVerticalSpacing(6)
        self.studyOptionsLayout1.setObjectName("studyOptionsLayout1")
        self.label_20 = QtGui.QLabel(self.studyOptionsFrame)
        self.label_20.setMinimumSize(QtCore.QSize(140, 0))
        self.label_20.setMargin(4)
        self.label_20.setObjectName("label_20")
        self.studyOptionsLayout1.addWidget(self.label_20, 1, 0, 1, 1)
        self.minuteLimit = QtGui.QLineEdit(self.studyOptionsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minuteLimit.sizePolicy().hasHeightForWidth())
        self.minuteLimit.setSizePolicy(sizePolicy)
        self.minuteLimit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.minuteLimit.setObjectName("minuteLimit")
        self.studyOptionsLayout1.addWidget(self.minuteLimit, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.studyOptionsFrame)
        self.label_22.setMinimumSize(QtCore.QSize(140, 0))
        self.label_22.setMargin(4)
        self.label_22.setObjectName("label_22")
        self.studyOptionsLayout1.addWidget(self.label_22, 0, 0, 1, 1)
        self.newPerDay = QtGui.QLineEdit(self.studyOptionsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newPerDay.sizePolicy().hasHeightForWidth())
        self.newPerDay.setSizePolicy(sizePolicy)
        self.newPerDay.setMaximumSize(QtCore.QSize(50, 16777215))
        self.newPerDay.setObjectName("newPerDay")
        self.studyOptionsLayout1.addWidget(self.newPerDay, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.studyOptionsLayout1.addItem(spacerItem3, 0, 2, 1, 1)
        self.questionLimit = QtGui.QLineEdit(self.studyOptionsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.questionLimit.sizePolicy().hasHeightForWidth())
        self.questionLimit.setSizePolicy(sizePolicy)
        self.questionLimit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.questionLimit.setObjectName("questionLimit")
        self.studyOptionsLayout1.addWidget(self.questionLimit, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.studyOptionsFrame)
        self.label.setMargin(4)
        self.label.setObjectName("label")
        self.studyOptionsLayout1.addWidget(self.label, 2, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.studyOptionsLayout1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.optionsBox = QtGui.QWidget(self.studyOptionsFrame)
        self.optionsBox.setObjectName("optionsBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.optionsBox)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setContentsMargins(2, 6, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.newCardOrder = QtGui.QComboBox(self.optionsBox)
        self.newCardOrder.setObjectName("newCardOrder")
        self.verticalLayout_7.addWidget(self.newCardOrder)
        self.newCardScheduling = QtGui.QComboBox(self.optionsBox)
        self.newCardScheduling.setObjectName("newCardScheduling")
        self.verticalLayout_7.addWidget(self.newCardScheduling)
        self.revCardOrder = QtGui.QComboBox(self.optionsBox)
        self.revCardOrder.setObjectName("revCardOrder")
        self.verticalLayout_7.addWidget(self.revCardOrder)
        self.failedCardsOption = QtGui.QComboBox(self.optionsBox)
        self.failedCardsOption.setObjectName("failedCardsOption")
        self.verticalLayout_7.addWidget(self.failedCardsOption)
        self.verticalLayout_12.addWidget(self.optionsBox)
        self.studyOptionsReviewBar = QtGui.QGridLayout()
        self.studyOptionsReviewBar.setContentsMargins(-1, 20, -1, -1)
        self.studyOptionsReviewBar.setHorizontalSpacing(10)
        self.studyOptionsReviewBar.setObjectName("studyOptionsReviewBar")
        self.startReviewingButton = QtGui.QPushButton(self.studyOptionsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startReviewingButton.sizePolicy().hasHeightForWidth())
        self.startReviewingButton.setSizePolicy(sizePolicy)
        self.startReviewingButton.setMinimumSize(QtCore.QSize(0, 26))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/player-time.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startReviewingButton.setIcon(icon2)
        self.startReviewingButton.setAutoDefault(True)
        self.startReviewingButton.setDefault(True)
        self.startReviewingButton.setObjectName("startReviewingButton")
        self.studyOptionsReviewBar.addWidget(self.startReviewingButton, 0, 0, 1, 1)
        self.optionsButton = QtGui.QPushButton(self.studyOptionsFrame)
        self.optionsButton.setMinimumSize(QtCore.QSize(0, 26))
        self.optionsButton.setCheckable(True)
        self.optionsButton.setChecked(False)
        self.optionsButton.setFlat(False)
        self.optionsButton.setObjectName("optionsButton")
        self.studyOptionsReviewBar.addWidget(self.optionsButton, 0, 1, 1, 1)
        self.optionsHelpButton = QtGui.QPushButton(self.studyOptionsFrame)
        self.optionsHelpButton.setMinimumSize(QtCore.QSize(0, 26))
        self.optionsHelpButton.setObjectName("optionsHelpButton")
        self.studyOptionsReviewBar.addWidget(self.optionsHelpButton, 0, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.studyOptionsReviewBar)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout_6.addLayout(self.verticalLayout_11)
        self.horizontalLayout_2.addWidget(self.studyOptionsFrame)
        spacerItem4 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtGui.QSpacerItem(20, 39, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.mainStack.addWidget(self.optionsPage)
        self.congratsPage = QtGui.QWidget()
        self.congratsPage.setObjectName("congratsPage")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.congratsPage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem6 = QtGui.QSpacerItem(20, 219, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.frame_2 = QtGui.QFrame(self.congratsPage)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setMargin(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem8 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem8)
        self.congratsLabel = QtGui.QLabel(self.frame_2)
        self.congratsLabel.setMargin(0)
        self.congratsLabel.setObjectName("congratsLabel")
        self.verticalLayout_10.addWidget(self.congratsLabel)
        spacerItem9 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem9)
        self.learnMoreButton = QtGui.QPushButton(self.frame_2)
        self.learnMoreButton.setIconSize(QtCore.QSize(32, 32))
        self.learnMoreButton.setObjectName("learnMoreButton")
        self.verticalLayout_10.addWidget(self.learnMoreButton)
        self.reviewEarlyButton = QtGui.QPushButton(self.frame_2)
        self.reviewEarlyButton.setIconSize(QtCore.QSize(32, 32))
        self.reviewEarlyButton.setObjectName("reviewEarlyButton")
        self.verticalLayout_10.addWidget(self.reviewEarlyButton)
        self.finishButton = QtGui.QPushButton(self.frame_2)
        self.finishButton.setAutoDefault(True)
        self.finishButton.setDefault(True)
        self.finishButton.setObjectName("finishButton")
        self.verticalLayout_10.addWidget(self.finishButton)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.horizontalLayout_3.addWidget(self.frame_2)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        spacerItem11 = QtGui.QSpacerItem(20, 219, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem11)
        self.mainStack.addWidget(self.congratsPage)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem12 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_15.addItem(spacerItem12)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem13 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.deckBrowserOuterFrame = QtGui.QFrame(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deckBrowserOuterFrame.sizePolicy().hasHeightForWidth())
        self.deckBrowserOuterFrame.setSizePolicy(sizePolicy)
        self.deckBrowserOuterFrame.setMinimumSize(QtCore.QSize(200, 200))
        self.deckBrowserOuterFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.deckBrowserOuterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.deckBrowserOuterFrame.setObjectName("deckBrowserOuterFrame")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.deckBrowserOuterFrame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setMargin(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_2 = QtGui.QLabel(self.deckBrowserOuterFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_14.addWidget(self.label_2)
        self.line_3 = QtGui.QFrame(self.deckBrowserOuterFrame)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_14.addWidget(self.line_3)
        self.deckBrowserSummary = QtGui.QLabel(self.deckBrowserOuterFrame)
        self.deckBrowserSummary.setAlignment(QtCore.Qt.AlignCenter)
        self.deckBrowserSummary.setObjectName("deckBrowserSummary")
        self.verticalLayout_14.addWidget(self.deckBrowserSummary)
        self.line_4 = QtGui.QFrame(self.deckBrowserOuterFrame)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_14.addWidget(self.line_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.verticalLayout_16 = QtGui.QHBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.downloadDeckButton = QtGui.QPushButton(self.deckBrowserOuterFrame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadDeckButton.setIcon(icon3)
        self.downloadDeckButton.setObjectName("downloadDeckButton")
        self.verticalLayout_16.addWidget(self.downloadDeckButton)
        self.newDeckButton = QtGui.QPushButton(self.deckBrowserOuterFrame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newDeckButton.setIcon(icon4)
        self.newDeckButton.setObjectName("newDeckButton")
        self.verticalLayout_16.addWidget(self.newDeckButton)
        self.importDeckButton = QtGui.QPushButton(self.deckBrowserOuterFrame)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/document-import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importDeckButton.setIcon(icon5)
        self.importDeckButton.setObjectName("importDeckButton")
        self.verticalLayout_16.addWidget(self.importDeckButton)
        self.horizontalLayout_7.addLayout(self.verticalLayout_16)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.verticalLayout_14.addLayout(self.horizontalLayout_7)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.horizontalLayout_5.addWidget(self.deckBrowserOuterFrame)
        spacerItem16 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        self.verticalLayout_15.addLayout(self.horizontalLayout_5)
        spacerItem17 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_15.addItem(spacerItem17)
        self.mainStack.addWidget(self.page)
        self.verticalLayout_18.addWidget(self.mainStack)
        self.buttonStack = QtGui.QStackedWidget(self.mainTextFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.buttonStack.sizePolicy().hasHeightForWidth())
        self.buttonStack.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.buttonStack.setPalette(palette)
        self.buttonStack.setAutoFillBackground(True)
        self.buttonStack.setObjectName("buttonStack")
        self.page1 = QtGui.QWidget()
        self.page1.setObjectName("page1")
        self.verticalLayout = QtGui.QVBoxLayout(self.page1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(8, 4, 8, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.showAnswerButton = QtGui.QPushButton(self.page1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showAnswerButton.sizePolicy().hasHeightForWidth())
        self.showAnswerButton.setSizePolicy(sizePolicy)
        self.showAnswerButton.setMinimumSize(QtCore.QSize(0, 41))
        self.showAnswerButton.setObjectName("showAnswerButton")
        self.horizontalLayout_4.addWidget(self.showAnswerButton)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem19)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.buttonStack.addWidget(self.page1)
        self.page2 = QtGui.QWidget()
        self.page2.setObjectName("page2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page2)
        self.verticalLayout_3.setContentsMargins(0, 4, 0, 4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem20 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem20)
        self.answerButtonLayout = QtGui.QGridLayout()
        self.answerButtonLayout.setContentsMargins(-1, 4, -1, 4)
        self.answerButtonLayout.setVerticalSpacing(0)
        self.answerButtonLayout.setObjectName("answerButtonLayout")
        self.easeLabel1 = QtGui.QLabel(self.page2)
        self.easeLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.easeLabel1.setObjectName("easeLabel1")
        self.answerButtonLayout.addWidget(self.easeLabel1, 0, 0, 1, 1)
        self.easeLabel2 = QtGui.QLabel(self.page2)
        self.easeLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.easeLabel2.setObjectName("easeLabel2")
        self.answerButtonLayout.addWidget(self.easeLabel2, 0, 1, 1, 1)
        self.easeLabel3 = QtGui.QLabel(self.page2)
        self.easeLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.easeLabel3.setObjectName("easeLabel3")
        self.answerButtonLayout.addWidget(self.easeLabel3, 0, 2, 1, 1)
        self.easeLabel4 = QtGui.QLabel(self.page2)
        self.easeLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.easeLabel4.setObjectName("easeLabel4")
        self.answerButtonLayout.addWidget(self.easeLabel4, 0, 3, 1, 1)
        self.easeButton1 = QtGui.QPushButton(self.page2)
        self.easeButton1.setObjectName("easeButton1")
        self.answerButtonLayout.addWidget(self.easeButton1, 1, 0, 1, 1)
        self.easeButton2 = QtGui.QPushButton(self.page2)
        self.easeButton2.setObjectName("easeButton2")
        self.answerButtonLayout.addWidget(self.easeButton2, 1, 1, 1, 1)
        self.easeButton3 = QtGui.QPushButton(self.page2)
        self.easeButton3.setObjectName("easeButton3")
        self.answerButtonLayout.addWidget(self.easeButton3, 1, 2, 1, 1)
        self.easeButton4 = QtGui.QPushButton(self.page2)
        self.easeButton4.setObjectName("easeButton4")
        self.answerButtonLayout.addWidget(self.easeButton4, 1, 3, 1, 1)
        self.horizontalLayout.addLayout(self.answerButtonLayout)
        spacerItem21 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem21)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.buttonStack.addWidget(self.page2)
        self.typeAnswerPage = QtGui.QWidget()
        self.typeAnswerPage.setObjectName("typeAnswerPage")
        self.buttonStack.addWidget(self.typeAnswerPage)
        self.blankButtonPage = QtGui.QWidget()
        self.blankButtonPage.setObjectName("blankButtonPage")
        self.buttonStack.addWidget(self.blankButtonPage)
        self.verticalLayout_18.addWidget(self.buttonStack)
        self.hboxlayout.addWidget(self.mainTextFrame)
        self.helpFrame = QtGui.QFrame(self.centralwidget)
        self.helpFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.helpFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.helpFrame.setObjectName("helpFrame")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.helpFrame)
        self.hboxlayout1.setSpacing(0)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.line = QtGui.QFrame(self.helpFrame)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout1.addWidget(self.line)
        self.innerHelpFrame = QtGui.QFrame(self.helpFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.innerHelpFrame.sizePolicy().hasHeightForWidth())
        self.innerHelpFrame.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.innerHelpFrame.setPalette(palette)
        self.innerHelpFrame.setAutoFillBackground(True)
        self.innerHelpFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.innerHelpFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.innerHelpFrame.setObjectName("innerHelpFrame")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.innerHelpFrame)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setMargin(9)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.help = QtGui.QTextBrowser(self.innerHelpFrame)
        self.help.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help.sizePolicy().hasHeightForWidth())
        self.help.setSizePolicy(sizePolicy)
        self.help.setMinimumSize(QtCore.QSize(250, 0))
        self.help.setMaximumSize(QtCore.QSize(300, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 169, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 126, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 253, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.help.setPalette(palette)
        self.help.setAutoFillBackground(True)
        self.help.setFrameShape(QtGui.QFrame.NoFrame)
        self.help.setFrameShadow(QtGui.QFrame.Sunken)
        self.help.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.help.setObjectName("help")
        self.hboxlayout2.addWidget(self.help)
        self.hboxlayout1.addWidget(self.innerHelpFrame)
        self.hboxlayout.addWidget(self.helpFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 23))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuDeck = QtGui.QMenu(self.menubar)
        self.menuDeck.setObjectName("menuDeck")
        self.menuDownload = QtGui.QMenu(self.menuDeck)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/document-open-remote.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuDownload.setIcon(icon6)
        self.menuDownload.setObjectName("menuDownload")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuAdvanced = QtGui.QMenu(self.menuTools)
        self.menuAdvanced.setObjectName("menuAdvanced")
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menuPlugins = QtGui.QMenu(self.menu_Settings)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/preferences-plugin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuPlugins.setIcon(icon7)
        self.menuPlugins.setObjectName("menuPlugins")
        self.menuStartup = QtGui.QMenu(self.menuPlugins)
        self.menuStartup.setObjectName("menuStartup")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon8)
        self.actionExit.setObjectName("actionExit")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setIcon(icon4)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon9)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/view_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon10)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon11)
        self.actionSave.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSave.setObjectName("actionSave")
        self.actionSyncdeck = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/multisynk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSyncdeck.setIcon(icon12)
        self.actionSyncdeck.setObjectName("actionSyncdeck")
        self.actionAddcards = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddcards.setIcon(icon13)
        self.actionAddcards.setObjectName("actionAddcards")
        self.actionEditdeck = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditdeck.setIcon(icon14)
        self.actionEditdeck.setObjectName("actionEditdeck")
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon15)
        self.actionPreferences.setMenuRole(QtGui.QAction.PreferencesRole)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionDstats = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/spreadsheet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDstats.setIcon(icon16)
        self.actionDstats.setObjectName("actionDstats")
        self.actionStarthere = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStarthere.setIcon(icon17)
        self.actionStarthere.setObjectName("actionStarthere")
        self.actionReportbug = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/kbugbuster.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReportbug.setIcon(icon18)
        self.actionReportbug.setObjectName("actionReportbug")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCstats = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/package_games_card.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCstats.setIcon(icon19)
        self.actionCstats.setObjectName("actionCstats")
        self.actionDeckProperties = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/contents.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeckProperties.setIcon(icon20)
        self.actionDeckProperties.setObjectName("actionDeckProperties")
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setIcon(icon5)
        self.actionImport.setObjectName("actionImport")
        self.actionGraphs = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/view-statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGraphs.setIcon(icon21)
        self.actionGraphs.setObjectName("actionGraphs")
        self.actionExport = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/document-export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon22)
        self.actionExport.setObjectName("actionExport")
        self.actionDisplayProperties = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/preferences-desktop-font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisplayProperties.setIcon(icon23)
        self.actionDisplayProperties.setObjectName("actionDisplayProperties")
        self.actionMarkCard = QtGui.QAction(MainWindow)
        self.actionMarkCard.setCheckable(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icons/rating.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMarkCard.setIcon(icon24)
        self.actionMarkCard.setObjectName("actionMarkCard")
        self.actionSuspendCard = QtGui.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/icons/media-playback-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSuspendCard.setIcon(icon25)
        self.actionSuspendCard.setObjectName("actionSuspendCard")
        self.actionRepeatAudio = QtGui.QAction(MainWindow)
        self.actionRepeatAudio.setEnabled(False)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/icons/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRepeatAudio.setIcon(icon26)
        self.actionRepeatAudio.setObjectName("actionRepeatAudio")
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setEnabled(False)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/icons/edit-undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon27)
        self.actionUndo.setObjectName("actionUndo")
        self.actionForum = QtGui.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/icons/view-pim-news.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionForum.setIcon(icon28)
        self.actionForum.setObjectName("actionForum")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/icons/document-save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon29)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionCheckDatabaseIntegrity = QtGui.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/icons/sqlitebrowser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheckDatabaseIntegrity.setIcon(icon30)
        self.actionCheckDatabaseIntegrity.setObjectName("actionCheckDatabaseIntegrity")
        self.actionOptimizeDatabase = QtGui.QAction(MainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/icons/games-solve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOptimizeDatabase.setIcon(icon31)
        self.actionOptimizeDatabase.setObjectName("actionOptimizeDatabase")
        self.actionCheckMediaDatabase = QtGui.QAction(MainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/icons/text-speak.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheckMediaDatabase.setIcon(icon32)
        self.actionCheckMediaDatabase.setObjectName("actionCheckMediaDatabase")
        self.actionCram = QtGui.QAction(MainWindow)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/icons/view-pim-calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCram.setIcon(icon33)
        self.actionCram.setObjectName("actionCram")
        self.actionReleaseNotes = QtGui.QAction(MainWindow)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/icons/kblogger.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReleaseNotes.setIcon(icon34)
        self.actionReleaseNotes.setObjectName("actionReleaseNotes")
        self.actionOpenPluginFolder = QtGui.QAction(MainWindow)
        self.actionOpenPluginFolder.setObjectName("actionOpenPluginFolder")
        self.actionEnableAllPlugins = QtGui.QAction(MainWindow)
        self.actionEnableAllPlugins.setObjectName("actionEnableAllPlugins")
        self.actionDisableAllPlugins = QtGui.QAction(MainWindow)
        self.actionDisableAllPlugins.setObjectName("actionDisableAllPlugins")
        self.actionActiveTags = QtGui.QAction(MainWindow)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/icons/anki-tag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionActiveTags.setIcon(icon35)
        self.actionActiveTags.setObjectName("actionActiveTags")
        self.actionEditCurrent = QtGui.QAction(MainWindow)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/icons/edit-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditCurrent.setIcon(icon36)
        self.actionEditCurrent.setObjectName("actionEditCurrent")
        self.actionRedo = QtGui.QAction(MainWindow)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/icons/edit-redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon37)
        self.actionRedo.setObjectName("actionRedo")
        self.actionDelete = QtGui.QAction(MainWindow)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/icons/editdelete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon38)
        self.actionDelete.setObjectName("actionDelete")
        self.actionCacheLatex = QtGui.QAction(MainWindow)
        self.actionCacheLatex.setObjectName("actionCacheLatex")
        self.actionUncacheLatex = QtGui.QAction(MainWindow)
        self.actionUncacheLatex.setObjectName("actionUncacheLatex")
        self.actionStudyOptions = QtGui.QAction(MainWindow)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/icons/chronometer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStudyOptions.setIcon(icon39)
        self.actionStudyOptions.setObjectName("actionStudyOptions")
        self.actionDonate = QtGui.QAction(MainWindow)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/icons/emblem-favorite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDonate.setIcon(icon40)
        self.actionDonate.setObjectName("actionDonate")
        self.actionRecordNoiseProfile = QtGui.QAction(MainWindow)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/icons/media-record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecordNoiseProfile.setIcon(icon41)
        self.actionRecordNoiseProfile.setObjectName("actionRecordNoiseProfile")
        self.actionOpenOnline = QtGui.QAction(MainWindow)
        self.actionOpenOnline.setObjectName("actionOpenOnline")
        self.actionDownloadSharedDeck = QtGui.QAction(MainWindow)
        self.actionDownloadSharedDeck.setObjectName("actionDownloadSharedDeck")
        self.actionDownloadSharedPlugin = QtGui.QAction(MainWindow)
        self.actionDownloadSharedPlugin.setObjectName("actionDownloadSharedPlugin")
        self.actionBuryFact = QtGui.QAction(MainWindow)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/icons/khtml_kget.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBuryFact.setIcon(icon42)
        self.actionBuryFact.setObjectName("actionBuryFact")
        self.actionFullDatabaseCheck = QtGui.QAction(MainWindow)
        self.actionFullDatabaseCheck.setObjectName("actionFullDatabaseCheck")
        self.actionOpenRecent = QtGui.QAction(MainWindow)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/icons/document-open-recent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenRecent.setIcon(icon43)
        self.actionOpenRecent.setObjectName("actionOpenRecent")
        self.actionDownloadMissingMedia = QtGui.QAction(MainWindow)
        self.actionDownloadMissingMedia.setObjectName("actionDownloadMissingMedia")
        self.actionExportOriginalFiles = QtGui.QAction(MainWindow)
        self.actionExportOriginalFiles.setObjectName("actionExportOriginalFiles")
        self.menuHelp.addAction(self.actionStarthere)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionReportbug)
        self.menuHelp.addAction(self.actionForum)
        self.menuHelp.addAction(self.actionReleaseNotes)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionDonate)
        self.menuHelp.addAction(self.actionAbout)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAddcards)
        self.menuEdit.addAction(self.actionEditCurrent)
        self.menuEdit.addAction(self.actionEditdeck)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionMarkCard)
        self.menuEdit.addAction(self.actionBuryFact)
        self.menuEdit.addAction(self.actionSuspendCard)
        self.menuEdit.addAction(self.actionDelete)
        self.menuDownload.addAction(self.actionOpenOnline)
        self.menuDownload.addSeparator()
        self.menuDownload.addAction(self.actionDownloadSharedDeck)
        self.menuDownload.addAction(self.actionDownloadSharedPlugin)
        self.menuDeck.addAction(self.actionNew)
        self.menuDeck.addAction(self.actionOpen)
        self.menuDeck.addAction(self.actionOpenRecent)
        self.menuDeck.addAction(self.menuDownload.menuAction())
        self.menuDeck.addAction(self.actionImport)
        self.menuDeck.addSeparator()
        self.menuDeck.addAction(self.actionSave)
        self.menuDeck.addAction(self.actionSaveAs)
        self.menuDeck.addAction(self.actionSyncdeck)
        self.menuDeck.addAction(self.actionExport)
        self.menuDeck.addSeparator()
        self.menuDeck.addAction(self.actionClose)
        self.menuDeck.addSeparator()
        self.menuDeck.addAction(self.actionExit)
        self.menuAdvanced.addAction(self.actionCheckDatabaseIntegrity)
        self.menuAdvanced.addAction(self.actionFullDatabaseCheck)
        self.menuAdvanced.addAction(self.actionOptimizeDatabase)
        self.menuAdvanced.addSeparator()
        self.menuAdvanced.addAction(self.actionCheckMediaDatabase)
        self.menuAdvanced.addAction(self.actionCacheLatex)
        self.menuAdvanced.addAction(self.actionUncacheLatex)
        self.menuAdvanced.addAction(self.actionDownloadMissingMedia)
        self.menuAdvanced.addAction(self.actionExportOriginalFiles)
        self.menuAdvanced.addSeparator()
        self.menuAdvanced.addAction(self.actionRecordNoiseProfile)
        self.menuAdvanced.addSeparator()
        self.menuTools.addAction(self.actionGraphs)
        self.menuTools.addAction(self.actionDstats)
        self.menuTools.addAction(self.actionCstats)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionRepeatAudio)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuAdvanced.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCram)
        self.menuTools.addSeparator()
        self.menuStartup.addAction(self.actionEnableAllPlugins)
        self.menuStartup.addAction(self.actionDisableAllPlugins)
        self.menuStartup.addSeparator()
        self.menuPlugins.addAction(self.actionOpenPluginFolder)
        self.menuPlugins.addSeparator()
        self.menuPlugins.addAction(self.menuStartup.menuAction())
        self.menuPlugins.addSeparator()
        self.menu_Settings.addAction(self.actionActiveTags)
        self.menu_Settings.addSeparator()
        self.menu_Settings.addAction(self.actionStudyOptions)
        self.menu_Settings.addAction(self.actionDisplayProperties)
        self.menu_Settings.addAction(self.actionDeckProperties)
        self.menu_Settings.addSeparator()
        self.menu_Settings.addAction(self.menuPlugins.menuAction())
        self.menu_Settings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuDeck.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSyncdeck)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAddcards)
        self.toolBar.addAction(self.actionEditCurrent)
        self.toolBar.addAction(self.actionEditdeck)
        self.toolBar.addAction(self.actionStudyOptions)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGraphs)
        self.toolBar.addAction(self.actionDstats)
        self.toolBar.addAction(self.actionCstats)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRepeatAudio)
        self.toolBar.addAction(self.actionMarkCard)

        self.retranslateUi(MainWindow)
        self.mainStack.setCurrentIndex(0)
        self.buttonStack.setCurrentIndex(3)
        QtCore.QObject.connect(self.optionsButton, QtCore.SIGNAL("toggled(bool)"), self.optionsBox.setShown)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.newPerDay, self.minuteLimit)
        MainWindow.setTabOrder(self.minuteLimit, self.questionLimit)
        MainWindow.setTabOrder(self.questionLimit, self.newCardOrder)
        MainWindow.setTabOrder(self.newCardOrder, self.newCardScheduling)
        MainWindow.setTabOrder(self.newCardScheduling, self.revCardOrder)
        MainWindow.setTabOrder(self.revCardOrder, self.failedCardsOption)
        MainWindow.setTabOrder(self.failedCardsOption, self.startReviewingButton)
        MainWindow.setTabOrder(self.startReviewingButton, self.optionsButton)
        MainWindow.setTabOrder(self.optionsButton, self.optionsHelpButton)
        MainWindow.setTabOrder(self.optionsHelpButton, self.learnMoreButton)
        MainWindow.setTabOrder(self.learnMoreButton, self.reviewEarlyButton)
        MainWindow.setTabOrder(self.reviewEarlyButton, self.finishButton)
        MainWindow.setTabOrder(self.finishButton, self.downloadDeckButton)
        MainWindow.setTabOrder(self.downloadDeckButton, self.newDeckButton)
        MainWindow.setTabOrder(self.newDeckButton, self.importDeckButton)
        MainWindow.setTabOrder(self.importDeckButton, self.easeButton1)
        MainWindow.setTabOrder(self.easeButton1, self.easeButton2)
        MainWindow.setTabOrder(self.easeButton2, self.easeButton3)
        MainWindow.setTabOrder(self.easeButton3, self.easeButton4)
        MainWindow.setTabOrder(self.easeButton4, self.saveEditorButton)
        MainWindow.setTabOrder(self.saveEditorButton, self.showAnswerButton)
        MainWindow.setTabOrder(self.showAnswerButton, self.help)
        MainWindow.setTabOrder(self.help, self.noticeButton)
        MainWindow.setTabOrder(self.noticeButton, self.welcomeText)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_("Anki"))
        self.noticeButton.setText(_("X"))
        self.saveEditorButton.setText(_("Continue Reviewing"))
        self.label_20.setToolTip(_("The <b>number of minutes in a session</b>. When a session is finished, this screen will be shown again, allowing you to start another session. Choose 0 for no limit."))
        self.label_20.setText(_("<b>Session limit (minutes):</b>"))
        self.label_22.setToolTip(_("The maximum number of <b>new cards shown per day</b>. The default is 20, to ensure you don\'t get overwhelmed with reviews after a few days."))
        self.label_22.setText(_("<b>New cards per day:</b>"))
        self.label.setToolTip(_("The <b>number of questions in a session</b>. When a session is finished, this screen will be shown again, allowing you to start another session. Choose 0 for no limit."))
        self.label.setText(_("<b>Session limit (questions)</b>:"))
        self.startReviewingButton.setText(_("Review"))
        self.optionsButton.setText(_("More"))
        self.optionsHelpButton.setText(_("Help"))
        self.learnMoreButton.setText(_("&Learn More"))
        self.reviewEarlyButton.setText(_("Re&view Early"))
        self.finishButton.setText(_("Fi&nish"))
        self.label_2.setText(_("<h1>Decks</h1>"))
        self.downloadDeckButton.setText(_("Download"))
        self.newDeckButton.setText(_("Create"))
        self.importDeckButton.setText(_("Import"))
        self.showAnswerButton.setToolTip(_("Show the answer (shortcut key: space or enter)"))
        self.showAnswerButton.setText(_("Show Answer"))
        self.easeButton1.setToolTip(_("Show this card again soon (shortcut key: 1)"))
        self.easeButton1.setText(_("Again"))
        self.easeButton2.setToolTip(_("Wait a little longer next time (shortcut key: 2)"))
        self.easeButton2.setText(_("Hard"))
        self.easeButton3.setToolTip(_("Wait longer next time (shortcut key: 3)"))
        self.easeButton3.setText(_("Good"))
        self.easeButton4.setToolTip(_("Wait a lot longer next time (shortcut key: 4)"))
        self.easeButton4.setText(_("Easy"))
        self.menuHelp.setTitle(_("&Help"))
        self.menuEdit.setTitle(_("&Edit"))
        self.menuDeck.setTitle(_("&File"))
        self.menuDownload.setTitle(_("&Download"))
        self.menuTools.setTitle(_("&Tools"))
        self.menuAdvanced.setTitle(_("Ad&vanced"))
        self.menu_Settings.setTitle(_("&Settings"))
        self.menuPlugins.setTitle(_("P&lugins"))
        self.menuStartup.setTitle(_("Startup"))
        self.actionExit.setText(_("E&xit"))
        self.actionExit.setShortcut(_("Ctrl+Q"))
        self.actionNew.setText(_("&New"))
        self.actionNew.setShortcut(_("Ctrl+N"))
        self.actionOpen.setText(_("&Open..."))
        self.actionOpen.setShortcut(_("Ctrl+O"))
        self.actionClose.setText(_("&Close"))
        self.actionClose.setStatusTip(_("Close this deck and return to the deck browser"))
        self.actionClose.setShortcut(_("Ctrl+W"))
        self.actionSave.setText(_("&Save"))
        self.actionSave.setStatusTip(_("Save this deck now"))
        self.actionSave.setShortcut(_("Ctrl+S"))
        self.actionSyncdeck.setText(_("S&ync"))
        self.actionSyncdeck.setStatusTip(_("Synchronize this deck with Anki Online"))
        self.actionSyncdeck.setShortcut(_("Ctrl+Y"))
        self.actionAddcards.setText(_("&Add Items..."))
        self.actionAddcards.setStatusTip(_("Add new items to Anki by typing them in"))
        self.actionAddcards.setShortcut(_("Ctrl+D"))
        self.actionEditdeck.setText(_("Brows&e Items..."))
        self.actionEditdeck.setStatusTip(_("Browse and edit all items"))
        self.actionEditdeck.setShortcut(_("Ctrl+F"))
        self.actionPreferences.setText(_("&Preferences"))
        self.actionPreferences.setStatusTip(_("Configure interface language and options"))
        self.actionPreferences.setShortcut(_("Ctrl+P"))
        self.actionDstats.setText(_("&Deck Statistics"))
        self.actionDstats.setStatusTip(_("Show some textual statistics about your deck"))
        self.actionStarthere.setText(_("Documentation"))
        self.actionStarthere.setShortcut(_("F1"))
        self.actionReportbug.setText(_("&Report Bug..."))
        self.actionReportbug.setWhatsThis(_("Open the bug tracker"))
        self.actionAbout.setText(_("&About..."))
        self.actionCstats.setText(_("&Card Statistics"))
        self.actionCstats.setStatusTip(_("Show statistics about the current card and last card"))
        self.actionDeckProperties.setText(_("&Deck Properties..."))
        self.actionDeckProperties.setStatusTip(_("Customize syncing, scheduling, priorities and models"))
        self.actionImport.setText(_("&Import..."))
        self.actionImport.setStatusTip(_("Import cards from text files, Anki files and more"))
        self.actionGraphs.setText(_("&Graphs..."))
        self.actionGraphs.setStatusTip(_("Show graphical statistics about your deck"))
        self.actionExport.setText(_("Expor&t..."))
        self.actionExport.setStatusTip(_("Save cards in a new deck or text file for sharing with others"))
        self.actionDisplayProperties.setText(_("&Fonts and Colours..."))
        self.actionDisplayProperties.setStatusTip(_("Customize fonts, colours and alignment"))
        self.actionMarkCard.setText(_("&Mark Fact"))
        self.actionMarkCard.setStatusTip(_("Apply the \'marked\' tag to this fact, so you find it later in the browser"))
        self.actionMarkCard.setShortcut(_("Ctrl+M"))
        self.actionSuspendCard.setText(_("&Suspend Card"))
        self.actionSuspendCard.setStatusTip(_("Stop reviewing this card until it\'s unsuspended in the browser"))
        self.actionSuspendCard.setShortcut(_("Ctrl+Shift+S"))
        self.actionRepeatAudio.setText(_("Repeat &Audio"))
        self.actionRepeatAudio.setStatusTip(_("Play the last-played audio again"))
        self.actionRepeatAudio.setShortcut(_("F5"))
        self.actionUndo.setText(_("&Undo"))
        self.actionUndo.setShortcut(_("Ctrl+Z"))
        self.actionForum.setText(_("&Forum..."))
        self.actionSaveAs.setText(_("Save &As..."))
        self.actionSaveAs.setStatusTip(_("Save this deck, giving it a new name"))
        self.actionCheckDatabaseIntegrity.setText(_("Quick Database Check"))
        self.actionCheckDatabaseIntegrity.setStatusTip(_("Check the database for errors"))
        self.actionOptimizeDatabase.setText(_("Optimize Database"))
        self.actionOptimizeDatabase.setStatusTip(_("Remove unused space, making the database file smaller"))
        self.actionCheckMediaDatabase.setText(_("Check Media Database..."))
        self.actionCheckMediaDatabase.setStatusTip(_("Check the files in the media directory"))
        self.actionCram.setText(_("C&ram..."))
        self.actionCram.setStatusTip(_("Do an extra review of specified cards before a test"))
        self.actionReleaseNotes.setText(_("Release Notes..."))
        self.actionOpenPluginFolder.setText(_("&Open Plugin Folder..."))
        self.actionEnableAllPlugins.setText(_("&Enable All Plugins"))
        self.actionDisableAllPlugins.setText(_("&Disable All Plugins"))
        self.actionActiveTags.setText(_("Inactive &Tags..."))
        self.actionActiveTags.setStatusTip(_("Choose the categories to show during review"))
        self.actionEditCurrent.setText(_("Edit &Current..."))
        self.actionEditCurrent.setStatusTip(_("Edit the currently displayed item"))
        self.actionEditCurrent.setShortcut(_("Ctrl+E"))
        self.actionRedo.setText(_("&Redo"))
        self.actionDelete.setText(_("&Delete Card"))
        self.actionDelete.setStatusTip(_("Delete the currently displayed card"))
        self.actionDelete.setShortcut(_("Ctrl+Del"))
        self.actionCacheLatex.setText(_("Cache LaTeX"))
        self.actionCacheLatex.setStatusTip(_("Pre-generate PNG images of LaTeX cards"))
        self.actionUncacheLatex.setText(_("Uncache LaTeX"))
        self.actionUncacheLatex.setStatusTip(_("Remove generated PNG images of LaTeX cards"))
        self.actionStudyOptions.setText(_("&Study Options..."))
        self.actionStudyOptions.setStatusTip(_("Configure review options"))
        self.actionDonate.setText(_("&Donate..."))
        self.actionRecordNoiseProfile.setText(_("&Record Noise Profile..."))
        self.actionRecordNoiseProfile.setStatusTip(_("Record 10 seconds of silence so that the record function can cancel noise"))
        self.actionOpenOnline.setText(_("Personal Deck..."))
        self.actionOpenOnline.setStatusTip(_("Download a deck that you synced from another computer"))
        self.actionDownloadSharedDeck.setText(_("Shared Deck..."))
        self.actionDownloadSharedDeck.setStatusTip(_("Download a deck that people have shared publicly"))
        self.actionDownloadSharedPlugin.setText(_("Shared Plugin..."))
        self.actionDownloadSharedPlugin.setStatusTip(_("Download a plugin to add new features or change Anki\'s behaviour"))
        self.actionBuryFact.setText(_("&Bury Fact"))
        self.actionBuryFact.setStatusTip(_("Suspend the current fact until the deck is closed and opened again"))
        self.actionBuryFact.setShortcut(_("Ctrl+Shift+B"))
        self.actionFullDatabaseCheck.setText(_("Full Database Check..."))
        self.actionOpenRecent.setText(_("Open Recent..."))
        self.actionOpenRecent.setShortcut(_("Ctrl+R"))
        self.actionDownloadMissingMedia.setText(_("Download Missing Media"))
        self.actionExportOriginalFiles.setText(_("Export Original Files"))
        self.actionExportOriginalFiles.setStatusTip(_("Save media files using original file names"))

import icons_rc
