# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/main.ui'
#

#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655,487)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/anki.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0,69,655,398))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setSpacing(0)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.mainTextFrame = QtGui.QFrame(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255,255,255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,QtGui.QPalette.Base,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,255,255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,QtGui.QPalette.Window,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,255,255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,QtGui.QPalette.Base,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,255,255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,QtGui.QPalette.Window,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,255,255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,QtGui.QPalette.Base,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,255,255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,QtGui.QPalette.Window,brush)
        self.mainTextFrame.setPalette(palette)
        self.mainTextFrame.setAutoFillBackground(True)
        self.mainTextFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.mainTextFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mainTextFrame.setObjectName("mainTextFrame")
        self.gridLayout = QtGui.QGridLayout(self.mainTextFrame)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(4,0,4,6)
        self.gridLayout.setObjectName("gridLayout")
        self.mainStack = QtGui.QStackedWidget(self.mainTextFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(99)
        sizePolicy.setHeightForWidth(self.mainStack.sizePolicy().hasHeightForWidth())
        self.mainStack.setSizePolicy(sizePolicy)
        self.mainStack.setObjectName("mainStack")
        self.blankPage = QtGui.QWidget()
        self.blankPage.setGeometry(QtCore.QRect(0,0,370,343))
        self.blankPage.setObjectName("blankPage")
        self.mainStack.addWidget(self.blankPage)
        self.welcomePage = QtGui.QWidget()
        self.welcomePage.setGeometry(QtCore.QRect(0,0,100,30))
        self.welcomePage.setObjectName("welcomePage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.welcomePage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.welcomeText = QtGui.QTextBrowser(self.welcomePage)
        self.welcomeText.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.welcomeText.setFrameShape(QtGui.QFrame.NoFrame)
        self.welcomeText.setObjectName("welcomeText")
        self.verticalLayout_5.addWidget(self.welcomeText)
        self.mainStack.addWidget(self.welcomePage)
        self.editPage = QtGui.QWidget()
        self.editPage.setGeometry(QtCore.QRect(0,0,100,30))
        self.editPage.setObjectName("editPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.editPage)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fieldsArea = QtGui.QWidget(self.editPage)
        self.fieldsArea.setObjectName("fieldsArea")
        self.verticalLayout_2.addWidget(self.fieldsArea)
        self.mainStack.addWidget(self.editPage)
        self.gridLayout.addWidget(self.mainStack,0,0,1,1)
        self.buttonStack = QtGui.QStackedWidget(self.mainTextFrame)
        self.buttonStack.setObjectName("buttonStack")
        self.page1 = QtGui.QWidget()
        self.page1.setGeometry(QtCore.QRect(0,0,100,30))
        self.page1.setObjectName("page1")
        self.verticalLayout = QtGui.QVBoxLayout(self.page1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20,1,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.showAnswerButton = QtGui.QPushButton(self.page1)
        self.showAnswerButton.setObjectName("showAnswerButton")
        self.verticalLayout.addWidget(self.showAnswerButton)
        self.buttonStack.addWidget(self.page1)
        self.page2 = QtGui.QWidget()
        self.page2.setGeometry(QtCore.QRect(0,0,100,30))
        self.page2.setObjectName("page2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0,0,0,6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(40,0,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.easeLabel1 = QtGui.QLabel(self.page2)
        self.easeLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.easeLabel1.setObjectName("easeLabel1")
        self.gridLayout_2.addWidget(self.easeLabel1,0,0,1,1)
        self.easeLabel2 = QtGui.QLabel(self.page2)
        self.easeLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.easeLabel2.setObjectName("easeLabel2")
        self.gridLayout_2.addWidget(self.easeLabel2,0,1,1,1)
        self.easeLabel3 = QtGui.QLabel(self.page2)
        self.easeLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.easeLabel3.setObjectName("easeLabel3")
        self.gridLayout_2.addWidget(self.easeLabel3,0,2,1,1)
        self.easeLabel4 = QtGui.QLabel(self.page2)
        self.easeLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.easeLabel4.setObjectName("easeLabel4")
        self.gridLayout_2.addWidget(self.easeLabel4,0,3,1,1)
        self.easeButton1 = QtGui.QPushButton(self.page2)
        self.easeButton1.setObjectName("easeButton1")
        self.gridLayout_2.addWidget(self.easeButton1,1,0,1,1)
        self.easeButton2 = QtGui.QPushButton(self.page2)
        self.easeButton2.setObjectName("easeButton2")
        self.gridLayout_2.addWidget(self.easeButton2,1,1,1,1)
        self.easeButton3 = QtGui.QPushButton(self.page2)
        self.easeButton3.setObjectName("easeButton3")
        self.gridLayout_2.addWidget(self.easeButton3,1,2,1,1)
        self.easeButton4 = QtGui.QPushButton(self.page2)
        self.easeButton4.setObjectName("easeButton4")
        self.gridLayout_2.addWidget(self.easeButton4,1,3,1,1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        spacerItem2 = QtGui.QSpacerItem(40,0,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.buttonStack.addWidget(self.page2)
        self.page3 = QtGui.QWidget()
        self.page3.setGeometry(QtCore.QRect(0,0,100,30))
        self.page3.setObjectName("page3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem3 = QtGui.QSpacerItem(20,1,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.saveEditorButton = QtGui.QPushButton(self.page3)
        self.saveEditorButton.setObjectName("saveEditorButton")
        self.verticalLayout_4.addWidget(self.saveEditorButton)
        self.buttonStack.addWidget(self.page3)
        self.page4 = QtGui.QWidget()
        self.page4.setGeometry(QtCore.QRect(0,0,370,49))
        self.page4.setObjectName("page4")
        self.buttonStack.addWidget(self.page4)
        self.gridLayout.addWidget(self.buttonStack,1,0,1,1)
        self.hboxlayout.addWidget(self.mainTextFrame)
        self.helpFrame = QtGui.QFrame(self.centralwidget)
        self.helpFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.helpFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.helpFrame.setObjectName("helpFrame")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.helpFrame)
        self.hboxlayout1.setSpacing(0)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.line = QtGui.QFrame(self.helpFrame)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout1.addWidget(self.line)
        self.innerHelpFrame = QtGui.QFrame(self.helpFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.innerHelpFrame.sizePolicy().hasHeightForWidth())
        self.innerHelpFrame.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255,255,255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,QtGui.QPalette.Base,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,250,230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,QtGui.QPalette.Window,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,255,255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,QtGui.QPalette.Base,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,250,230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,QtGui.QPalette.Window,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,250,230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,QtGui.QPalette.Base,brush)
        brush = QtGui.QBrush(QtGui.QColor(207,207,207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,QtGui.QPalette.Window,brush)
        self.innerHelpFrame.setPalette(palette)
        self.innerHelpFrame.setAutoFillBackground(True)
        self.innerHelpFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.innerHelpFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.innerHelpFrame.setObjectName("innerHelpFrame")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.innerHelpFrame)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setMargin(9)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.help = QtGui.QTextBrowser(self.innerHelpFrame)
        self.help.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help.sizePolicy().hasHeightForWidth())
        self.help.setSizePolicy(sizePolicy)
        self.help.setMaximumSize(QtCore.QSize(300,16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255,250,230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,QtGui.QPalette.Base,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,250,230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,QtGui.QPalette.Base,brush)
        brush = QtGui.QBrush(QtGui.QColor(207,207,207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,QtGui.QPalette.Base,brush)
        self.help.setPalette(palette)
        self.help.setFrameShape(QtGui.QFrame.NoFrame)
        self.help.setFrameShadow(QtGui.QFrame.Sunken)
        self.help.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.help.setObjectName("help")
        self.hboxlayout2.addWidget(self.help)
        self.hboxlayout1.addWidget(self.innerHelpFrame)
        self.hboxlayout.addWidget(self.helpFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,655,23))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuDeck = QtGui.QMenu(self.menubar)
        self.menuDeck.setObjectName("menuDeck")
        self.menuOpenRecent = QtGui.QMenu(self.menuDeck)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/document-open-recent.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.menuOpenRecent.setIcon(icon)
        self.menuOpenRecent.setObjectName("menuOpenRecent")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menu_Lookup = QtGui.QMenu(self.menuTools)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/edit-find.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.menu_Lookup.setIcon(icon)
        self.menu_Lookup.setObjectName("menu_Lookup")
        self.menuAdvanced = QtGui.QMenu(self.menuTools)
        self.menuAdvanced.setObjectName("menuAdvanced")
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menuPlugins = QtGui.QMenu(self.menu_Settings)
        self.menuPlugins.setObjectName("menuPlugins")
        self.menuStartup = QtGui.QMenu(self.menuPlugins)
        self.menuStartup.setObjectName("menuStartup")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0,467,655,20))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setGeometry(QtCore.QRect(0,23,655,46))
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(32,32))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea,self.toolBar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/application-exit.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionNew = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/document-new.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/document-open.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/fileclose.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionClose.setIcon(icon)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/document-save.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionSyncdeck = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/multisynk.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionSyncdeck.setIcon(icon)
        self.actionSyncdeck.setObjectName("actionSyncdeck")
        self.actionAddcards = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/list-add.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionAddcards.setIcon(icon)
        self.actionAddcards.setObjectName("actionAddcards")
        self.actionEditdeck = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/view_text.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionEditdeck.setIcon(icon)
        self.actionEditdeck.setObjectName("actionEditdeck")
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/configure.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon)
        self.actionPreferences.setMenuRole(QtGui.QAction.PreferencesRole)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionLookup_expr = QtGui.QAction(MainWindow)
        self.actionLookup_expr.setObjectName("actionLookup_expr")
        self.actionLookup_mean = QtGui.QAction(MainWindow)
        self.actionLookup_mean.setObjectName("actionLookup_mean")
        self.actionLookup_as = QtGui.QAction(MainWindow)
        self.actionLookup_as.setObjectName("actionLookup_as")
        self.actionLookup_es = QtGui.QAction(MainWindow)
        self.actionLookup_es.setObjectName("actionLookup_es")
        self.actionLookup_esk = QtGui.QAction(MainWindow)
        self.actionLookup_esk.setObjectName("actionLookup_esk")
        self.actionKstats = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/kanji.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionKstats.setIcon(icon)
        self.actionKstats.setObjectName("actionKstats")
        self.actionDstats = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/spreadsheet.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionDstats.setIcon(icon)
        self.actionDstats.setObjectName("actionDstats")
        self.actionStarthere = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/go-home.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionStarthere.setIcon(icon)
        self.actionStarthere.setObjectName("actionStarthere")
        self.actionReportbug = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/kbugbuster.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionReportbug.setIcon(icon)
        self.actionReportbug.setObjectName("actionReportbug")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/anki.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCstats = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/package_games_card.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionCstats.setIcon(icon)
        self.actionCstats.setObjectName("actionCstats")
        self.actionDeckProperties = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/contents.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionDeckProperties.setIcon(icon)
        self.actionDeckProperties.setObjectName("actionDeckProperties")
        self.actionImport = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/document-import.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionImport.setIcon(icon)
        self.actionImport.setObjectName("actionImport")
        self.actionGraphs = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/colorscm.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionGraphs.setIcon(icon)
        self.actionGraphs.setObjectName("actionGraphs")
        self.actionExport = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/document-export.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionExport.setIcon(icon)
        self.actionExport.setObjectName("actionExport")
        self.actionDisplayProperties = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/preferences-desktop-font.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionDisplayProperties.setIcon(icon)
        self.actionDisplayProperties.setObjectName("actionDisplayProperties")
        self.actionOpenSamples = QtGui.QAction(MainWindow)
        self.actionOpenSamples.setObjectName("actionOpenSamples")
        self.actionMarkCard = QtGui.QAction(MainWindow)
        self.actionMarkCard.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/rating.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionMarkCard.setIcon(icon)
        self.actionMarkCard.setObjectName("actionMarkCard")
        self.actionSuspendCard = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/media-playback-pause.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionSuspendCard.setIcon(icon)
        self.actionSuspendCard.setObjectName("actionSuspendCard")
        self.actionModelProperties = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/kpersonalizer.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionModelProperties.setIcon(icon)
        self.actionModelProperties.setObjectName("actionModelProperties")
        self.actionRepeatQuestionAudio = QtGui.QAction(MainWindow)
        self.actionRepeatQuestionAudio.setObjectName("actionRepeatQuestionAudio")
        self.actionRepeatAnswerAudio = QtGui.QAction(MainWindow)
        self.actionRepeatAnswerAudio.setObjectName("actionRepeatAnswerAudio")
        self.actionRepeatAudio = QtGui.QAction(MainWindow)
        self.actionRepeatAudio.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/media-playback-start.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionRepeatAudio.setIcon(icon)
        self.actionRepeatAudio.setObjectName("actionRepeatAudio")
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/edit-undo.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon)
        self.actionUndo.setObjectName("actionUndo")
        self.actionForum = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/view-pim-news.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionForum.setIcon(icon)
        self.actionForum.setObjectName("actionForum")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/document-save-as.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionCheckDatabaseIntegrity = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/sqlitebrowser.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionCheckDatabaseIntegrity.setIcon(icon)
        self.actionCheckDatabaseIntegrity.setObjectName("actionCheckDatabaseIntegrity")
        self.actionOptimizeDatabase = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/games-solve.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionOptimizeDatabase.setIcon(icon)
        self.actionOptimizeDatabase.setObjectName("actionOptimizeDatabase")
        self.actionMergeModels = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/khtml_kget.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionMergeModels.setIcon(icon)
        self.actionMergeModels.setObjectName("actionMergeModels")
        self.actionCheckMediaDatabase = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/text-speak.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionCheckMediaDatabase.setIcon(icon)
        self.actionCheckMediaDatabase.setObjectName("actionCheckMediaDatabase")
        self.actionOpenOnline = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/document-open-remote.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionOpenOnline.setIcon(icon)
        self.actionOpenOnline.setObjectName("actionOpenOnline")
        self.actionCram = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/chronometer.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionCram.setIcon(icon)
        self.actionCram.setObjectName("actionCram")
        self.actionReleaseNotes = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/kblogger.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionReleaseNotes.setIcon(icon)
        self.actionReleaseNotes.setObjectName("actionReleaseNotes")
        self.actionGetPlugins = QtGui.QAction(MainWindow)
        self.actionGetPlugins.setObjectName("actionGetPlugins")
        self.actionOpenPluginFolder = QtGui.QAction(MainWindow)
        self.actionOpenPluginFolder.setObjectName("actionOpenPluginFolder")
        self.actionEnableAllPlugins = QtGui.QAction(MainWindow)
        self.actionEnableAllPlugins.setObjectName("actionEnableAllPlugins")
        self.actionDisableAllPlugins = QtGui.QAction(MainWindow)
        self.actionDisableAllPlugins.setObjectName("actionDisableAllPlugins")
        self.actionA = QtGui.QAction(MainWindow)
        self.actionA.setObjectName("actionA")
        self.actionActiveTags = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/anki-tag.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionActiveTags.setIcon(icon)
        self.actionActiveTags.setObjectName("actionActiveTags")
        self.actionGetMoreDecks = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/khtml_kget.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionGetMoreDecks.setIcon(icon)
        self.actionGetMoreDecks.setObjectName("actionGetMoreDecks")
        self.actionEditCurrent = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/edit-rename.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionEditCurrent.setIcon(icon)
        self.actionEditCurrent.setObjectName("actionEditCurrent")
        self.actionRedo = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/edit-redo.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon)
        self.actionRedo.setObjectName("actionRedo")
        self.actionDelete = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/editdelete.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon)
        self.actionDelete.setObjectName("actionDelete")
        self.action123 = QtGui.QAction(MainWindow)
        self.action123.setObjectName("action123")
        self.action_Delete_Fact = QtGui.QAction(MainWindow)
        self.action_Delete_Fact.setObjectName("action_Delete_Fact")
        self.actionCacheLatex = QtGui.QAction(MainWindow)
        self.actionCacheLatex.setObjectName("actionCacheLatex")
        self.actionUncacheLatex = QtGui.QAction(MainWindow)
        self.actionUncacheLatex.setObjectName("actionUncacheLatex")
        self.menuHelp.addAction(self.actionStarthere)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionReportbug)
        self.menuHelp.addAction(self.actionForum)
        self.menuHelp.addAction(self.actionReleaseNotes)
        self.menuHelp.addAction(self.actionGetMoreDecks)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAddcards)
        self.menuEdit.addAction(self.actionEditCurrent)
        self.menuEdit.addAction(self.actionEditdeck)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionMarkCard)
        self.menuEdit.addAction(self.actionSuspendCard)
        self.menuEdit.addAction(self.actionDelete)
        self.menuDeck.addAction(self.actionNew)
        self.menuDeck.addAction(self.actionOpen)
        self.menuDeck.addAction(self.menuOpenRecent.menuAction())
        self.menuDeck.addAction(self.actionOpenOnline)
        self.menuDeck.addAction(self.actionImport)
        self.menuDeck.addSeparator()
        self.menuDeck.addAction(self.actionSave)
        self.menuDeck.addAction(self.actionSaveAs)
        self.menuDeck.addAction(self.actionSyncdeck)
        self.menuDeck.addAction(self.actionExport)
        self.menuDeck.addSeparator()
        self.menuDeck.addAction(self.actionClose)
        self.menuDeck.addSeparator()
        self.menuDeck.addAction(self.actionExit)
        self.menu_Lookup.addAction(self.actionLookup_expr)
        self.menu_Lookup.addAction(self.actionLookup_mean)
        self.menu_Lookup.addSeparator()
        self.menu_Lookup.addAction(self.actionLookup_as)
        self.menu_Lookup.addAction(self.actionLookup_es)
        self.menu_Lookup.addAction(self.actionLookup_esk)
        self.menuAdvanced.addAction(self.actionCheckDatabaseIntegrity)
        self.menuAdvanced.addAction(self.actionOptimizeDatabase)
        self.menuAdvanced.addSeparator()
        self.menuAdvanced.addAction(self.actionCheckMediaDatabase)
        self.menuAdvanced.addAction(self.actionCacheLatex)
        self.menuAdvanced.addAction(self.actionUncacheLatex)
        self.menuAdvanced.addSeparator()
        self.menuAdvanced.addAction(self.actionMergeModels)
        self.menuAdvanced.addSeparator()
        self.menuTools.addAction(self.actionGraphs)
        self.menuTools.addAction(self.actionDstats)
        self.menuTools.addAction(self.actionKstats)
        self.menuTools.addAction(self.actionCstats)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionRepeatAudio)
        self.menuTools.addAction(self.menu_Lookup.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuAdvanced.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCram)
        self.menuStartup.addAction(self.actionEnableAllPlugins)
        self.menuStartup.addAction(self.actionDisableAllPlugins)
        self.menuStartup.addSeparator()
        self.menuPlugins.addAction(self.actionGetPlugins)
        self.menuPlugins.addAction(self.actionOpenPluginFolder)
        self.menuPlugins.addSeparator()
        self.menuPlugins.addAction(self.menuStartup.menuAction())
        self.menu_Settings.addAction(self.actionActiveTags)
        self.menu_Settings.addSeparator()
        self.menu_Settings.addAction(self.actionDisplayProperties)
        self.menu_Settings.addAction(self.actionModelProperties)
        self.menu_Settings.addAction(self.actionDeckProperties)
        self.menu_Settings.addSeparator()
        self.menu_Settings.addAction(self.menuPlugins.menuAction())
        self.menu_Settings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuDeck.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSyncdeck)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAddcards)
        self.toolBar.addAction(self.actionEditCurrent)
        self.toolBar.addAction(self.actionEditdeck)
        self.toolBar.addAction(self.actionDisplayProperties)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGraphs)
        self.toolBar.addAction(self.actionDstats)
        self.toolBar.addAction(self.actionCstats)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRepeatAudio)
        self.toolBar.addAction(self.actionMarkCard)

        self.retranslateUi(MainWindow)
        self.mainStack.setCurrentIndex(0)
        self.buttonStack.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_("Anki"))
        self.showAnswerButton.setText(_("Show Answer"))
        self.easeButton1.setText(_("Again"))
        self.easeButton2.setText(_("Hard"))
        self.easeButton3.setText(_("Good"))
        self.easeButton4.setText(_("Easy"))
        self.saveEditorButton.setText(_("Close"))
        self.saveEditorButton.setShortcut(_("Esc"))
        self.menuHelp.setTitle(_("&Help"))
        self.menuEdit.setTitle(_("&Edit"))
        self.menuDeck.setTitle(_("&File"))
        self.menuOpenRecent.setTitle(_("Open &Recent"))
        self.menuTools.setTitle(_("&Tools"))
        self.menu_Lookup.setTitle(_("&Lookup"))
        self.menuAdvanced.setTitle(_("Ad&vanced"))
        self.menu_Settings.setTitle(_("&Settings"))
        self.menuPlugins.setTitle(_("P&lugins"))
        self.menuStartup.setTitle(_("Startup"))
        self.actionExit.setText(_("E&xit"))
        self.actionExit.setShortcut(_("Ctrl+Q"))
        self.actionNew.setText(_("&New..."))
        self.actionNew.setShortcut(_("Ctrl+N"))
        self.actionOpen.setText(_("&Open..."))
        self.actionOpen.setShortcut(_("Ctrl+O"))
        self.actionClose.setText(_("&Close"))
        self.actionClose.setShortcut(_("Ctrl+W"))
        self.actionSave.setText(_("&Save"))
        self.actionSave.setShortcut(_("Ctrl+S"))
        self.actionSyncdeck.setText(_("Save and S&ync"))
        self.actionSyncdeck.setShortcut(_("Ctrl+Y"))
        self.actionAddcards.setText(_("&Add Items..."))
        self.actionAddcards.setShortcut(_("Ctrl+D"))
        self.actionEditdeck.setText(_("&Edit All..."))
        self.actionEditdeck.setShortcut(_("Ctrl+F"))
        self.actionPreferences.setText(_("&Preferences"))
        self.actionPreferences.setStatusTip(_("Application-wide preferences."))
        self.actionPreferences.setShortcut(_("Ctrl+P"))
        self.actionLookup_expr.setText(_("...&expression on ALC"))
        self.actionLookup_expr.setShortcut(_("Ctrl+1"))
        self.actionLookup_mean.setText(_("...&meaning on ALC"))
        self.actionLookup_mean.setShortcut(_("Ctrl+2"))
        self.actionLookup_as.setText(_("...&selection on ALC"))
        self.actionLookup_as.setShortcut(_("Ctrl+3"))
        self.actionLookup_es.setText(_("...&word selection on Edict"))
        self.actionLookup_es.setShortcut(_("Ctrl+4"))
        self.actionLookup_esk.setText(_("...&kanji selection on Edict"))
        self.actionLookup_esk.setShortcut(_("Ctrl+5"))
        self.actionKstats.setText(_("&Kanji Statistics"))
        self.actionDstats.setText(_("&Deck Statistics"))
        self.actionStarthere.setText(_("&Start Here..."))
        self.actionReportbug.setText(_("&Report Bug..."))
        self.actionReportbug.setWhatsThis(_("Open the bug tracker."))
        self.actionAbout.setText(_("&About..."))
        self.actionCstats.setText(_("&Card Statistics"))
        self.actionDeckProperties.setText(_("&Deck Properties..."))
        self.actionDeckProperties.setStatusTip(_("Customize syncing, scheduling, priorities and models."))
        self.actionImport.setText(_("&Import..."))
        self.actionGraphs.setText(_("&Graphs..."))
        self.actionExport.setText(_("Expor&t..."))
        self.actionDisplayProperties.setText(_("&Fonts and Colours..."))
        self.actionDisplayProperties.setStatusTip(_("Customize fonts, colours and alignment."))
        self.actionOpenSamples.setText(_("Open Sa&mple..."))
        self.actionMarkCard.setText(_("&Mark Fact"))
        self.actionMarkCard.setShortcut(_("Ctrl+M"))
        self.actionSuspendCard.setText(_("&Suspend Fact"))
        self.actionSuspendCard.setStatusTip(_("Stop reviewing this card until it\'s unsuspended in the editor."))
        self.actionModelProperties.setText(_("Current &Model..."))
        self.actionModelProperties.setStatusTip(_("Customize card layout, fields, etc."))
        self.actionRepeatQuestionAudio.setText(_("Repeat &Question Audio"))
        self.actionRepeatAnswerAudio.setText(_("Repeat &Answer Audio"))
        self.actionRepeatAudio.setText(_("Repeat &Audio"))
        self.actionRepeatAudio.setShortcut(_("F5"))
        self.actionUndo.setText(_("&Undo"))
        self.actionUndo.setShortcut(_("Ctrl+Z"))
        self.actionForum.setText(_("&Forum..."))
        self.actionSaveAs.setText(_("Save &As..."))
        self.actionCheckDatabaseIntegrity.setText(_("Check Database..."))
        self.actionOptimizeDatabase.setText(_("Optimize Database"))
        self.actionMergeModels.setText(_("Merge Models..."))
        self.actionCheckMediaDatabase.setText(_("Check Media Database..."))
        self.actionOpenOnline.setText(_("Open On&line..."))
        self.actionCram.setText(_("C&ram..."))
        self.actionReleaseNotes.setText(_("Release Notes..."))
        self.actionGetPlugins.setText(_("&Get Plugins..."))
        self.actionOpenPluginFolder.setText(_("&Open Plugin Folder..."))
        self.actionEnableAllPlugins.setText(_("&Enable All Plugins"))
        self.actionDisableAllPlugins.setText(_("&Disable All Plugins"))
        self.actionA.setText(_("a"))
        self.actionActiveTags.setText(_("Active &Tags..."))
        self.actionGetMoreDecks.setText(_("&Get More Decks..."))
        self.actionEditCurrent.setText(_("Edit &Current..."))
        self.actionEditCurrent.setShortcut(_("Ctrl+E"))
        self.actionRedo.setText(_("&Redo"))
        self.actionDelete.setText(_("&Delete Card"))
        self.action123.setText(_("123"))
        self.action_Delete_Fact.setText(_("&Delete Fact"))
        self.actionCacheLatex.setText(_("Cache LaTeX"))
        self.actionUncacheLatex.setText(_("Uncache LaTeX"))

import icons_rc
