# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/modelproperties.ui'
#

#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ModelProperties(object):
    def setupUi(self, ModelProperties):
        ModelProperties.setObjectName("ModelProperties")
        ModelProperties.setWindowModality(QtCore.Qt.ApplicationModal)
        ModelProperties.resize(420, 551)
        self.verticalLayout = QtGui.QVBoxLayout(ModelProperties)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(ModelProperties)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.vboxlayout = QtGui.QVBoxLayout(self.tab_2)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.vboxlayout.addWidget(self.label_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(4)
        self.gridLayout.setContentsMargins(4, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.name = QtGui.QLineEdit(self.tab_2)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.tags = QtGui.QLineEdit(self.tab_2)
        self.tags.setObjectName("tags")
        self.gridLayout.addWidget(self.tags, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setOpenExternalLinks(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_2)
        self.label_25.setOpenExternalLinks(True)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.initialSpacing = QtGui.QLineEdit(self.tab_2)
        self.initialSpacing.setObjectName("initialSpacing")
        self.horizontalLayout_3.addWidget(self.initialSpacing)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.spacing = QtGui.QLineEdit(self.tab_2)
        self.spacing.setObjectName("spacing")
        self.horizontalLayout_4.addWidget(self.spacing)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.mediaURL = QtGui.QLineEdit(self.tab_2)
        self.mediaURL.setObjectName("mediaURL")
        self.gridLayout.addWidget(self.mediaURL, 4, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridLayout)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.vboxlayout.addWidget(self.line_3)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.vboxlayout.addWidget(self.label_6)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.fieldList = QtGui.QListWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldList.sizePolicy().hasHeightForWidth())
        self.fieldList.setSizePolicy(sizePolicy)
        self.fieldList.setMinimumSize(QtCore.QSize(0, 60))
        self.fieldList.setObjectName("fieldList")
        self.hboxlayout.addWidget(self.fieldList)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fieldAdd = QtGui.QPushButton(self.tab_2)
        self.fieldAdd.setAutoDefault(False)
        self.fieldAdd.setObjectName("fieldAdd")
        self.horizontalLayout.addWidget(self.fieldAdd)
        self.fieldUp = QtGui.QPushButton(self.tab_2)
        self.fieldUp.setAutoDefault(False)
        self.fieldUp.setObjectName("fieldUp")
        self.horizontalLayout.addWidget(self.fieldUp)
        self.fieldDown = QtGui.QPushButton(self.tab_2)
        self.fieldDown.setAutoDefault(False)
        self.fieldDown.setObjectName("fieldDown")
        self.horizontalLayout.addWidget(self.fieldDown)
        self.fieldDelete = QtGui.QPushButton(self.tab_2)
        self.fieldDelete.setAutoDefault(False)
        self.fieldDelete.setObjectName("fieldDelete")
        self.horizontalLayout.addWidget(self.fieldDelete)
        self.vboxlayout.addLayout(self.horizontalLayout)
        self.fieldEditBox = QtGui.QGroupBox(self.tab_2)
        self.fieldEditBox.setTitle("")
        self.fieldEditBox.setFlat(False)
        self.fieldEditBox.setObjectName("fieldEditBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.fieldEditBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self._2 = QtGui.QGridLayout()
        self._2.setMargin(0)
        self._2.setSpacing(6)
        self._2.setObjectName("_2")
        self.label_18 = QtGui.QLabel(self.fieldEditBox)
        self.label_18.setObjectName("label_18")
        self._2.addWidget(self.label_18, 1, 0, 1, 1)
        self.fieldName = QtGui.QLineEdit(self.fieldEditBox)
        self.fieldName.setObjectName("fieldName")
        self._2.addWidget(self.fieldName, 0, 1, 1, 1)
        self.fieldUnique = QtGui.QCheckBox(self.fieldEditBox)
        self.fieldUnique.setObjectName("fieldUnique")
        self._2.addWidget(self.fieldUnique, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.fieldEditBox)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self._2.addWidget(self.label_20, 0, 0, 1, 1)
        self.fieldRequired = QtGui.QCheckBox(self.fieldEditBox)
        self.fieldRequired.setObjectName("fieldRequired")
        self._2.addWidget(self.fieldRequired, 2, 1, 1, 1)
        self.numeric = QtGui.QCheckBox(self.fieldEditBox)
        self.numeric.setObjectName("numeric")
        self._2.addWidget(self.numeric, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self._2)
        self.vboxlayout.addWidget(self.fieldEditBox)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.cardList = QtGui.QListWidget(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cardList.sizePolicy().hasHeightForWidth())
        self.cardList.setSizePolicy(sizePolicy)
        self.cardList.setMinimumSize(QtCore.QSize(0, 60))
        self.cardList.setObjectName("cardList")
        self.hboxlayout1.addWidget(self.cardList)
        self.gridLayout_2.addLayout(self.hboxlayout1, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cardAdd = QtGui.QPushButton(self.tab_3)
        self.cardAdd.setObjectName("cardAdd")
        self.horizontalLayout_2.addWidget(self.cardAdd)
        self.cardUp = QtGui.QPushButton(self.tab_3)
        self.cardUp.setObjectName("cardUp")
        self.horizontalLayout_2.addWidget(self.cardUp)
        self.cardDown = QtGui.QPushButton(self.tab_3)
        self.cardDown.setObjectName("cardDown")
        self.horizontalLayout_2.addWidget(self.cardDown)
        self.cardToggle = QtGui.QPushButton(self.tab_3)
        self.cardToggle.setText("")
        self.cardToggle.setObjectName("cardToggle")
        self.horizontalLayout_2.addWidget(self.cardToggle)
        self.cardDelete = QtGui.QPushButton(self.tab_3)
        self.cardDelete.setObjectName("cardDelete")
        self.horizontalLayout_2.addWidget(self.cardDelete)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.cardEditBox = QtGui.QGroupBox(self.tab_3)
        self.cardEditBox.setTitle("")
        self.cardEditBox.setObjectName("cardEditBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.cardEditBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self._3 = QtGui.QGridLayout()
        self._3.setMargin(0)
        self._3.setSpacing(6)
        self._3.setObjectName("_3")
        self.label_23 = QtGui.QLabel(self.cardEditBox)
        self.label_23.setObjectName("label_23")
        self._3.addWidget(self.label_23, 3, 0, 1, 1)
        self.cardAnswer = QtGui.QTextEdit(self.cardEditBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardAnswer.sizePolicy().hasHeightForWidth())
        self.cardAnswer.setSizePolicy(sizePolicy)
        self.cardAnswer.setMaximumSize(QtCore.QSize(16777215, 60))
        self.cardAnswer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cardAnswer.setTabChangesFocus(True)
        self.cardAnswer.setAcceptRichText(False)
        self.cardAnswer.setObjectName("cardAnswer")
        self._3.addWidget(self.cardAnswer, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.cardEditBox)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setOpenExternalLinks(True)
        self.label_15.setObjectName("label_15")
        self._3.addWidget(self.label_15, 2, 0, 1, 1)
        self.cardName = QtGui.QLineEdit(self.cardEditBox)
        self.cardName.setObjectName("cardName")
        self._3.addWidget(self.cardName, 0, 1, 1, 1)
        self.cardQuestion = QtGui.QTextEdit(self.cardEditBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardQuestion.sizePolicy().hasHeightForWidth())
        self.cardQuestion.setSizePolicy(sizePolicy)
        self.cardQuestion.setMaximumSize(QtCore.QSize(16777215, 60))
        self.cardQuestion.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cardQuestion.setTabChangesFocus(True)
        self.cardQuestion.setObjectName("cardQuestion")
        self._3.addWidget(self.cardQuestion, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.cardEditBox)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setOpenExternalLinks(True)
        self.label_12.setObjectName("label_12")
        self._3.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.cardEditBox)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setOpenExternalLinks(True)
        self.label_14.setObjectName("label_14")
        self._3.addWidget(self.label_14, 1, 0, 1, 1)
        self.typeAnswer = QtGui.QComboBox(self.cardEditBox)
        self.typeAnswer.setObjectName("typeAnswer")
        self._3.addWidget(self.typeAnswer, 3, 1, 1, 1)
        self.questionInAnswer = QtGui.QCheckBox(self.cardEditBox)
        self.questionInAnswer.setObjectName("questionInAnswer")
        self._3.addWidget(self.questionInAnswer, 4, 1, 1, 1)
        self.allowEmptyAnswer = QtGui.QCheckBox(self.cardEditBox)
        self.allowEmptyAnswer.setObjectName("allowEmptyAnswer")
        self._3.addWidget(self.allowEmptyAnswer, 5, 1, 1, 1)
        self.verticalLayout_3.addLayout(self._3)
        self.gridLayout_2.addWidget(self.cardEditBox, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(ModelProperties)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ModelProperties)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ModelProperties.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ModelProperties.reject)
        QtCore.QMetaObject.connectSlotsByName(ModelProperties)
        ModelProperties.setTabOrder(self.tabWidget, self.name)
        ModelProperties.setTabOrder(self.name, self.tags)
        ModelProperties.setTabOrder(self.tags, self.initialSpacing)
        ModelProperties.setTabOrder(self.initialSpacing, self.spacing)
        ModelProperties.setTabOrder(self.spacing, self.mediaURL)
        ModelProperties.setTabOrder(self.mediaURL, self.fieldList)
        ModelProperties.setTabOrder(self.fieldList, self.fieldAdd)
        ModelProperties.setTabOrder(self.fieldAdd, self.fieldUp)
        ModelProperties.setTabOrder(self.fieldUp, self.fieldDown)
        ModelProperties.setTabOrder(self.fieldDown, self.fieldDelete)
        ModelProperties.setTabOrder(self.fieldDelete, self.fieldName)
        ModelProperties.setTabOrder(self.fieldName, self.fieldUnique)
        ModelProperties.setTabOrder(self.fieldUnique, self.fieldRequired)
        ModelProperties.setTabOrder(self.fieldRequired, self.numeric)
        ModelProperties.setTabOrder(self.numeric, self.cardList)
        ModelProperties.setTabOrder(self.cardList, self.cardAdd)
        ModelProperties.setTabOrder(self.cardAdd, self.cardUp)
        ModelProperties.setTabOrder(self.cardUp, self.cardDown)
        ModelProperties.setTabOrder(self.cardDown, self.cardToggle)
        ModelProperties.setTabOrder(self.cardToggle, self.cardDelete)
        ModelProperties.setTabOrder(self.cardDelete, self.cardName)
        ModelProperties.setTabOrder(self.cardName, self.cardQuestion)
        ModelProperties.setTabOrder(self.cardQuestion, self.cardAnswer)
        ModelProperties.setTabOrder(self.cardAnswer, self.typeAnswer)
        ModelProperties.setTabOrder(self.typeAnswer, self.questionInAnswer)
        ModelProperties.setTabOrder(self.questionInAnswer, self.allowEmptyAnswer)
        ModelProperties.setTabOrder(self.allowEmptyAnswer, self.buttonBox)

    def retranslateUi(self, ModelProperties):
        ModelProperties.setWindowTitle(_("Model Properties"))
        self.label_2.setText(_("<h1>General</h1>"))
        self.label.setText(_("<b>Name</b>"))
        self.label_3.setText(_("<b>Tags</b>"))
        self.label_19.setText(_("<b>Minimum spacing</b>"))
        self.label_25.setText(_("<b>Spacing multipler</b>"))
        self.label_4.setText(_("<b>Media URL</B>"))
        self.label_6.setText(_("<h1>Fields</h1>"))
        self.fieldAdd.setText(_("&Add"))
        self.fieldUp.setToolTip(_("Move selected field up"))
        self.fieldUp.setText(_("Move &Up"))
        self.fieldDown.setToolTip(_("Move selected field down"))
        self.fieldDown.setText(_("Move Dow&n"))
        self.fieldDelete.setText(_("&Delete"))
        self.label_18.setText(_("<b>Options</b>"))
        self.fieldUnique.setText(_("Prevent duplicates"))
        self.label_20.setText(_("<b>Name</b>"))
        self.fieldRequired.setText(_("Prevent empty entries"))
        self.numeric.setText(_("Sort as numbers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("General && Fields"))
        self.label_8.setText(_("<h1>Card Templates</h1>"))
        self.cardAdd.setText(_("&Add"))
        self.cardUp.setToolTip(_("Move selected card model up"))
        self.cardUp.setText(_("Move &Up"))
        self.cardDown.setToolTip(_("Move selected card model down"))
        self.cardDown.setText(_("Move Dow&n"))
        self.cardDelete.setText(_("&Delete"))
        self.label_23.setText(_("<b>Options</b>"))
        self.label_15.setText(_("<b>Answer</b>"))
        self.label_12.setText(_("<b>Name</b>"))
        self.label_14.setText(_("<b>Question</b>"))
        self.questionInAnswer.setText(_("Hide the question when showing answer"))
        self.allowEmptyAnswer.setText(_("Allow the answer to be blank"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _("Card Templates"))

