# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/preferences.ui'
#

#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(322,417)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Preferences)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(Preferences)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setGeometry(QtCore.QRect(0,0,306,351))
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtGui.QLabel(self.tab_1)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.interfaceLang = QtGui.QComboBox(self.tab_1)
        self.interfaceLang.setMinimumSize(QtCore.QSize(300,0))
        self.interfaceLang.setObjectName("interfaceLang")
        self.vboxlayout.addWidget(self.interfaceLang)
        self.label_2 = QtGui.QLabel(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.vboxlayout.addWidget(self.label_2)
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.label_8 = QtGui.QLabel(self.tab_1)
        self.label_8.setObjectName("label_8")
        self.gridlayout.addWidget(self.label_8,0,0,1,1)
        self.label_13 = QtGui.QLabel(self.tab_1)
        self.label_13.setObjectName("label_13")
        self.gridlayout.addWidget(self.label_13,1,0,1,1)
        self.interfaceColour = QtGui.QPushButton(self.tab_1)
        self.interfaceColour.setObjectName("interfaceColour")
        self.gridlayout.addWidget(self.interfaceColour,1,1,1,1)
        self.label_15 = QtGui.QLabel(self.tab_1)
        self.label_15.setObjectName("label_15")
        self.gridlayout.addWidget(self.label_15,2,0,1,1)
        self.backgroundColour = QtGui.QPushButton(self.tab_1)
        self.backgroundColour.setObjectName("backgroundColour")
        self.gridlayout.addWidget(self.backgroundColour,2,1,1,1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.interfaceFamily = QtGui.QFontComboBox(self.tab_1)
        self.interfaceFamily.setMaximumSize(QtCore.QSize(140,16777215))
        self.interfaceFamily.setObjectName("interfaceFamily")
        self.horizontalLayout_2.addWidget(self.interfaceFamily)
        self.interfaceSize = QtGui.QSpinBox(self.tab_1)
        self.interfaceSize.setMaximum(300)
        self.interfaceSize.setObjectName("interfaceSize")
        self.horizontalLayout_2.addWidget(self.interfaceSize)
        self.gridlayout.addLayout(self.horizontalLayout_2,0,1,1,1)
        self.vboxlayout.addLayout(self.gridlayout)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.vboxlayout.addLayout(self.gridlayout1)
        self.verticalLayout.addLayout(self.vboxlayout)
        self.showDivider = QtGui.QCheckBox(self.tab_1)
        self.showDivider.setObjectName("showDivider")
        self.verticalLayout.addWidget(self.showDivider)
        self.splitQA = QtGui.QCheckBox(self.tab_1)
        self.splitQA.setObjectName("splitQA")
        self.verticalLayout.addWidget(self.splitQA)
        self.suppressEstimates = QtGui.QCheckBox(self.tab_1)
        self.suppressEstimates.setObjectName("suppressEstimates")
        self.verticalLayout.addWidget(self.suppressEstimates)
        spacerItem = QtGui.QSpacerItem(20,0,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_1,"")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setGeometry(QtCore.QRect(0,0,306,351))
        self.tab_2.setObjectName("tab_2")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.tab_2)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(9)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.vboxlayout2.addWidget(self.label_4)
        self.saveWhenClosing = QtGui.QCheckBox(self.tab_2)
        self.saveWhenClosing.setChecked(True)
        self.saveWhenClosing.setObjectName("saveWhenClosing")
        self.vboxlayout2.addWidget(self.saveWhenClosing)
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setMargin(0)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.saveAfterEvery = QtGui.QCheckBox(self.tab_2)
        self.saveAfterEvery.setChecked(True)
        self.saveAfterEvery.setObjectName("saveAfterEvery")
        self.gridlayout2.addWidget(self.saveAfterEvery,1,0,1,1)
        self.saveAfterEveryNum = QtGui.QSpinBox(self.tab_2)
        self.saveAfterEveryNum.setObjectName("saveAfterEveryNum")
        self.gridlayout2.addWidget(self.saveAfterEveryNum,1,1,1,1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridlayout2.addWidget(self.label_5,1,2,1,1)
        self.saveAfterAdding = QtGui.QCheckBox(self.tab_2)
        self.saveAfterAdding.setChecked(True)
        self.saveAfterAdding.setObjectName("saveAfterAdding")
        self.gridlayout2.addWidget(self.saveAfterAdding,2,0,1,1)
        self.saveAfterAddingNum = QtGui.QSpinBox(self.tab_2)
        self.saveAfterAddingNum.setObjectName("saveAfterAddingNum")
        self.gridlayout2.addWidget(self.saveAfterAddingNum,2,1,1,1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridlayout2.addWidget(self.label_7,2,2,1,1)
        self.vboxlayout2.addLayout(self.gridlayout2)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setWordWrap(True)
        self.label_16.setOpenExternalLinks(True)
        self.label_16.setObjectName("label_16")
        self.vboxlayout2.addWidget(self.label_16)
        self.gridlayout3 = QtGui.QGridLayout()
        self.gridlayout3.setMargin(0)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.gridlayout3.addWidget(self.label_18,1,0,1,1)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.gridlayout3.addWidget(self.label_17,0,0,1,1)
        self.syncUser = QtGui.QLineEdit(self.tab_2)
        self.syncUser.setObjectName("syncUser")
        self.gridlayout3.addWidget(self.syncUser,0,1,1,1)
        self.syncOnClose = QtGui.QCheckBox(self.tab_2)
        self.syncOnClose.setChecked(True)
        self.syncOnClose.setObjectName("syncOnClose")
        self.gridlayout3.addWidget(self.syncOnClose,3,0,1,1)
        self.syncPass = QtGui.QLineEdit(self.tab_2)
        self.syncPass.setEchoMode(QtGui.QLineEdit.Password)
        self.syncPass.setObjectName("syncPass")
        self.gridlayout3.addWidget(self.syncPass,1,1,1,1)
        self.syncOnOpen = QtGui.QCheckBox(self.tab_2)
        self.syncOnOpen.setChecked(True)
        self.syncOnOpen.setObjectName("syncOnOpen")
        self.gridlayout3.addWidget(self.syncOnOpen,2,0,1,1)
        self.vboxlayout2.addLayout(self.gridlayout3)
        self.hboxlayout.addLayout(self.vboxlayout2)
        self.vboxlayout1.addLayout(self.hboxlayout)
        spacerItem1 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2,"")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setGeometry(QtCore.QRect(0,0,306,351))
        self.tab_3.setObjectName("tab_3")
        self.vboxlayout3 = QtGui.QVBoxLayout(self.tab_3)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.gridlayout4 = QtGui.QGridLayout()
        self.gridlayout4.setObjectName("gridlayout4")
        self.simpleToolbar = QtGui.QCheckBox(self.tab_3)
        self.simpleToolbar.setObjectName("simpleToolbar")
        self.gridlayout4.addWidget(self.simpleToolbar,3,0,1,1)
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.gridlayout4.addWidget(self.label_6,2,0,1,1)
        self.showTimer = QtGui.QCheckBox(self.tab_3)
        self.showTimer.setObjectName("showTimer")
        self.gridlayout4.addWidget(self.showTimer,4,0,1,1)
        self.showLastCardContent = QtGui.QCheckBox(self.tab_3)
        self.showLastCardContent.setObjectName("showLastCardContent")
        self.gridlayout4.addWidget(self.showLastCardContent,5,0,1,1)
        self.showLastCardInterval = QtGui.QCheckBox(self.tab_3)
        self.showLastCardInterval.setObjectName("showLastCardInterval")
        self.gridlayout4.addWidget(self.showLastCardInterval,6,0,1,1)
        self.showToolbar = QtGui.QCheckBox(self.tab_3)
        self.showToolbar.setObjectName("showToolbar")
        self.gridlayout4.addWidget(self.showToolbar,7,0,1,1)
        self.tallButtons = QtGui.QCheckBox(self.tab_3)
        self.tallButtons.setObjectName("tallButtons")
        self.gridlayout4.addWidget(self.tallButtons,8,0,1,1)
        self.showTray = QtGui.QCheckBox(self.tab_3)
        self.showTray.setObjectName("showTray")
        self.gridlayout4.addWidget(self.showTray,9,0,1,1)
        self.scrollToAnswer = QtGui.QCheckBox(self.tab_3)
        self.scrollToAnswer.setObjectName("scrollToAnswer")
        self.gridlayout4.addWidget(self.scrollToAnswer,10,0,1,1)
        self.addZeroSpace = QtGui.QCheckBox(self.tab_3)
        self.addZeroSpace.setObjectName("addZeroSpace")
        self.gridlayout4.addWidget(self.addZeroSpace,11,0,1,1)
        self.alternativeTheme = QtGui.QCheckBox(self.tab_3)
        self.alternativeTheme.setObjectName("alternativeTheme")
        self.gridlayout4.addWidget(self.alternativeTheme,12,0,1,1)
        self.vboxlayout3.addLayout(self.gridlayout4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        spacerItem2 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.toolbarIconSize = QtGui.QLineEdit(self.tab_3)
        self.toolbarIconSize.setObjectName("toolbarIconSize")
        self.horizontalLayout.addWidget(self.toolbarIconSize)
        self.vboxlayout3.addLayout(self.horizontalLayout)
        spacerItem3 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_3,"")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Preferences)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("accepted()"),Preferences.accept)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("rejected()"),Preferences.reject)
        QtCore.QObject.connect(self.saveAfterEvery,QtCore.SIGNAL("toggled(bool)"),self.saveAfterEveryNum.setEnabled)
        QtCore.QObject.connect(self.saveAfterAdding,QtCore.SIGNAL("toggled(bool)"),self.saveAfterAddingNum.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Preferences)
        Preferences.setTabOrder(self.tabWidget,self.interfaceLang)
        Preferences.setTabOrder(self.interfaceLang,self.label_2)
        Preferences.setTabOrder(self.label_2,self.interfaceFamily)
        Preferences.setTabOrder(self.interfaceFamily,self.interfaceSize)
        Preferences.setTabOrder(self.interfaceSize,self.interfaceColour)
        Preferences.setTabOrder(self.interfaceColour,self.backgroundColour)
        Preferences.setTabOrder(self.backgroundColour,self.showDivider)
        Preferences.setTabOrder(self.showDivider,self.splitQA)
        Preferences.setTabOrder(self.splitQA,self.suppressEstimates)
        Preferences.setTabOrder(self.suppressEstimates,self.saveWhenClosing)
        Preferences.setTabOrder(self.saveWhenClosing,self.saveAfterEvery)
        Preferences.setTabOrder(self.saveAfterEvery,self.saveAfterEveryNum)
        Preferences.setTabOrder(self.saveAfterEveryNum,self.saveAfterAdding)
        Preferences.setTabOrder(self.saveAfterAdding,self.saveAfterAddingNum)
        Preferences.setTabOrder(self.saveAfterAddingNum,self.syncUser)
        Preferences.setTabOrder(self.syncUser,self.syncPass)
        Preferences.setTabOrder(self.syncPass,self.syncOnOpen)
        Preferences.setTabOrder(self.syncOnOpen,self.syncOnClose)
        Preferences.setTabOrder(self.syncOnClose,self.simpleToolbar)
        Preferences.setTabOrder(self.simpleToolbar,self.showTimer)
        Preferences.setTabOrder(self.showTimer,self.showLastCardContent)
        Preferences.setTabOrder(self.showLastCardContent,self.showLastCardInterval)
        Preferences.setTabOrder(self.showLastCardInterval,self.showToolbar)
        Preferences.setTabOrder(self.showToolbar,self.tallButtons)
        Preferences.setTabOrder(self.tallButtons,self.showTray)
        Preferences.setTabOrder(self.showTray,self.scrollToAnswer)
        Preferences.setTabOrder(self.scrollToAnswer,self.addZeroSpace)
        Preferences.setTabOrder(self.addZeroSpace,self.alternativeTheme)
        Preferences.setTabOrder(self.alternativeTheme,self.toolbarIconSize)
        Preferences.setTabOrder(self.toolbarIconSize,self.buttonBox)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(_("Preferences"))
        self.label.setText(_("<h1>Language</h1>"))
        self.label_2.setText(_("<h1>Main Window</h1>"))
        self.label_8.setText(_("Interface font"))
        self.label_13.setText(_("Interface colour"))
        self.label_15.setText(_("Background colour"))
        self.showDivider.setText(_("Show divider between question and answer"))
        self.splitQA.setText(_("Put space between question and answer"))
        self.suppressEstimates.setText(_("Don\'t show next time before answer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _("Display"))
        self.label_4.setText(_("<h1>Autosaving</h1>"))
        self.saveWhenClosing.setText(_("Save when closing"))
        self.saveAfterEvery.setText(_("Save after answering"))
        self.label_5.setText(_("cards"))
        self.saveAfterAdding.setText(_("Save after adding"))
        self.label_7.setText(_("facts"))
        self.label_16.setText(_("<h1>Synchronisation</h1><a href=\"http://anki.ichi2.net/\">Create a free account</a>."))
        self.label_18.setText(_("Password"))
        self.label_17.setText(_("Username"))
        self.syncOnClose.setText(_("Sync on close"))
        self.syncOnOpen.setText(_("Sync on open"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("Save && Sync"))
        self.simpleToolbar.setText(_("Simple toolbar"))
        self.label_6.setText(_("<h1>Advanced settings</h1>"))
        self.showTimer.setText(_("Show timer"))
        self.showLastCardContent.setText(_("Show last card\'s question/answer"))
        self.showLastCardInterval.setText(_("Show last card\'s interval"))
        self.showToolbar.setText(_("Show toolbar on startup"))
        self.tallButtons.setText(_("Tall buttons (for touchscreen)"))
        self.showTray.setText(_("Show tray icon"))
        self.scrollToAnswer.setText(_("Scroll down to the answer when showing answer"))
        self.addZeroSpace.setText(_("Add hidden char to text (fixes Thai on OSX)"))
        self.alternativeTheme.setText(_("Alternative theme"))
        self.label_11.setText(_("Toolbar icon size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _("Advanced"))

