# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/preferences.ui'
#

#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(320,399)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Preferences)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(Preferences)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setGeometry(QtCore.QRect(0,0,304,333))
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.tab_1)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.interfaceLang = QtGui.QComboBox(self.tab_1)
        self.interfaceLang.setMinimumSize(QtCore.QSize(300,0))
        self.interfaceLang.setObjectName("interfaceLang")
        self.verticalLayout.addWidget(self.interfaceLang)
        self.label_2 = QtGui.QLabel(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.showDivider = QtGui.QCheckBox(self.tab_1)
        self.showDivider.setObjectName("showDivider")
        self.verticalLayout.addWidget(self.showDivider)
        self.splitQA = QtGui.QCheckBox(self.tab_1)
        self.splitQA.setObjectName("splitQA")
        self.verticalLayout.addWidget(self.splitQA)
        self.showEstimates = QtGui.QCheckBox(self.tab_1)
        self.showEstimates.setObjectName("showEstimates")
        self.verticalLayout.addWidget(self.showEstimates)
        spacerItem = QtGui.QSpacerItem(20,0,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_1,"")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setGeometry(QtCore.QRect(0,0,304,333))
        self.tab_2.setObjectName("tab_2")
        self.vboxlayout = QtGui.QVBoxLayout(self.tab_2)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.vboxlayout1.addWidget(self.label_4)
        self.saveWhenClosing = QtGui.QCheckBox(self.tab_2)
        self.saveWhenClosing.setChecked(True)
        self.saveWhenClosing.setObjectName("saveWhenClosing")
        self.vboxlayout1.addWidget(self.saveWhenClosing)
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.saveAfterEvery = QtGui.QCheckBox(self.tab_2)
        self.saveAfterEvery.setChecked(True)
        self.saveAfterEvery.setObjectName("saveAfterEvery")
        self.gridlayout.addWidget(self.saveAfterEvery,1,0,1,1)
        self.saveAfterEveryNum = QtGui.QSpinBox(self.tab_2)
        self.saveAfterEveryNum.setObjectName("saveAfterEveryNum")
        self.gridlayout.addWidget(self.saveAfterEveryNum,1,1,1,1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridlayout.addWidget(self.label_5,1,2,1,1)
        self.saveAfterAdding = QtGui.QCheckBox(self.tab_2)
        self.saveAfterAdding.setChecked(True)
        self.saveAfterAdding.setObjectName("saveAfterAdding")
        self.gridlayout.addWidget(self.saveAfterAdding,2,0,1,1)
        self.saveAfterAddingNum = QtGui.QSpinBox(self.tab_2)
        self.saveAfterAddingNum.setObjectName("saveAfterAddingNum")
        self.gridlayout.addWidget(self.saveAfterAddingNum,2,1,1,1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridlayout.addWidget(self.label_7,2,2,1,1)
        self.vboxlayout1.addLayout(self.gridlayout)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setWordWrap(True)
        self.label_16.setOpenExternalLinks(True)
        self.label_16.setObjectName("label_16")
        self.vboxlayout1.addWidget(self.label_16)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.gridlayout1.addWidget(self.label_18,1,0,1,1)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.gridlayout1.addWidget(self.label_17,0,0,1,1)
        self.syncUser = QtGui.QLineEdit(self.tab_2)
        self.syncUser.setObjectName("syncUser")
        self.gridlayout1.addWidget(self.syncUser,0,1,1,1)
        self.syncOnClose = QtGui.QCheckBox(self.tab_2)
        self.syncOnClose.setChecked(True)
        self.syncOnClose.setObjectName("syncOnClose")
        self.gridlayout1.addWidget(self.syncOnClose,3,0,1,1)
        self.syncPass = QtGui.QLineEdit(self.tab_2)
        self.syncPass.setEchoMode(QtGui.QLineEdit.Password)
        self.syncPass.setObjectName("syncPass")
        self.gridlayout1.addWidget(self.syncPass,1,1,1,1)
        self.syncOnOpen = QtGui.QCheckBox(self.tab_2)
        self.syncOnOpen.setChecked(True)
        self.syncOnOpen.setObjectName("syncOnOpen")
        self.gridlayout1.addWidget(self.syncOnOpen,2,0,1,1)
        self.vboxlayout1.addLayout(self.gridlayout1)
        self.hboxlayout.addLayout(self.vboxlayout1)
        self.vboxlayout.addLayout(self.hboxlayout)
        spacerItem1 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2,"")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setGeometry(QtCore.QRect(0,0,304,333))
        self.tab_3.setObjectName("tab_3")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.tab_3)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setObjectName("gridlayout2")
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.gridlayout2.addWidget(self.label_6,2,0,1,1)
        self.showTimer = QtGui.QCheckBox(self.tab_3)
        self.showTimer.setObjectName("showTimer")
        self.gridlayout2.addWidget(self.showTimer,5,0,1,1)
        spacerItem2 = QtGui.QSpacerItem(20,10,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Fixed)
        self.gridlayout2.addItem(spacerItem2,3,0,1,1)
        self.alternativeTheme = QtGui.QCheckBox(self.tab_3)
        self.alternativeTheme.setObjectName("alternativeTheme")
        self.gridlayout2.addWidget(self.alternativeTheme,4,0,1,1)
        self.showStudyOptions = QtGui.QCheckBox(self.tab_3)
        self.showStudyOptions.setObjectName("showStudyOptions")
        self.gridlayout2.addWidget(self.showStudyOptions,7,0,1,1)
        self.showTray = QtGui.QCheckBox(self.tab_3)
        self.showTray.setObjectName("showTray")
        self.gridlayout2.addWidget(self.showTray,6,0,1,1)
        self.addZeroSpace = QtGui.QCheckBox(self.tab_3)
        self.addZeroSpace.setObjectName("addZeroSpace")
        self.gridlayout2.addWidget(self.addZeroSpace,8,0,1,1)
        self.vboxlayout2.addLayout(self.gridlayout2)
        spacerItem3 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout2.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_3,"")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Preferences)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("accepted()"),Preferences.accept)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("rejected()"),Preferences.reject)
        QtCore.QObject.connect(self.saveAfterEvery,QtCore.SIGNAL("toggled(bool)"),self.saveAfterEveryNum.setEnabled)
        QtCore.QObject.connect(self.saveAfterAdding,QtCore.SIGNAL("toggled(bool)"),self.saveAfterAddingNum.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Preferences)
        Preferences.setTabOrder(self.tabWidget,self.interfaceLang)
        Preferences.setTabOrder(self.interfaceLang,self.label_2)
        Preferences.setTabOrder(self.label_2,self.showDivider)
        Preferences.setTabOrder(self.showDivider,self.splitQA)
        Preferences.setTabOrder(self.splitQA,self.showEstimates)
        Preferences.setTabOrder(self.showEstimates,self.saveWhenClosing)
        Preferences.setTabOrder(self.saveWhenClosing,self.saveAfterEvery)
        Preferences.setTabOrder(self.saveAfterEvery,self.saveAfterEveryNum)
        Preferences.setTabOrder(self.saveAfterEveryNum,self.saveAfterAdding)
        Preferences.setTabOrder(self.saveAfterAdding,self.saveAfterAddingNum)
        Preferences.setTabOrder(self.saveAfterAddingNum,self.syncUser)
        Preferences.setTabOrder(self.syncUser,self.syncPass)
        Preferences.setTabOrder(self.syncPass,self.syncOnOpen)
        Preferences.setTabOrder(self.syncOnOpen,self.syncOnClose)
        Preferences.setTabOrder(self.syncOnClose,self.alternativeTheme)
        Preferences.setTabOrder(self.alternativeTheme,self.showTimer)
        Preferences.setTabOrder(self.showTimer,self.showStudyOptions)
        Preferences.setTabOrder(self.showStudyOptions,self.buttonBox)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(_("Preferences"))
        self.label.setText(_("<h1>Language</h1>"))
        self.label_2.setText(_("<h1>Reviewing</h1>"))
        self.showDivider.setText(_("Show divider between question and answer"))
        self.splitQA.setText(_("Put space between question and answer"))
        self.showEstimates.setText(_("Show next time before answer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _("Display"))
        self.label_4.setText(_("<h1>Autosaving</h1>"))
        self.saveWhenClosing.setText(_("Save when closing"))
        self.saveAfterEvery.setText(_("Save after answering"))
        self.label_5.setText(_("cards"))
        self.saveAfterAdding.setText(_("Save after adding"))
        self.label_7.setText(_("facts"))
        self.label_16.setText(_("<h1>Synchronisation</h1><a href=\"http://anki.ichi2.net/\">Create a free account</a>."))
        self.label_18.setText(_("Password"))
        self.label_17.setText(_("Username"))
        self.syncOnClose.setText(_("Sync on close"))
        self.syncOnOpen.setText(_("Sync on open"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("Save && Sync"))
        self.label_6.setText(_("<h1>Advanced settings</h1>Some settings require a restart."))
        self.showTimer.setText(_("Show timer"))
        self.alternativeTheme.setText(_("Alternative theme"))
        self.showStudyOptions.setText(_("Show welcome back screen on startup"))
        self.showTray.setText(_("Show tray icon"))
        self.addZeroSpace.setText(_("Add hidden char to text (fixes Thai on OSX)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _("Advanced"))

